// GENERATED by wiregen — DO NOT EDIT
// schema_sha256=019b629d0cc8374708a62af3177a1f22d06dd0b817a22a32db6dd34a61137142
using System;
using System.Buffers.Binary;
using System.Text;

namespace Speculum.Wire;

public static class SchemaMeta { public const string Sha256 = "019b629d0cc8374708a62af3177a1f22d06dd0b817a22a32db6dd34a61137142"; public const int MessageCount = 48; }

public ref struct CursorReader {
  ReadOnlySpan<byte> _b; int _o; public bool Ok { get; private set; } = true;
  public CursorReader(ReadOnlySpan<byte> b) { _b = b; _o = 0; }
  bool Need(int n) { if (_o + n > _b.Length) { Ok = false; return false; } return true; }
  public byte U8() { if (!Need(1)) return 0; var v = _b[_o]; _o += 1; return v; }
  public ushort U16() { if (!Need(2)) return 0; var v = BinaryPrimitives.ReadUInt16LittleEndian(_b.Slice(_o)); _o += 2; return v; }
  public uint U32() { if (!Need(4)) return 0; var v = BinaryPrimitives.ReadUInt32LittleEndian(_b.Slice(_o)); _o += 4; return v; }
  public ulong U64() { if (!Need(8)) return 0; var v = BinaryPrimitives.ReadUInt64LittleEndian(_b.Slice(_o)); _o += 8; return v; }
  public int I32() { if (!Need(4)) return 0; var v = BinaryPrimitives.ReadInt32LittleEndian(_b.Slice(_o)); _o += 4; return v; }
  public bool Bool() => U8() != 0;
  public string Str() { var n = (int)U32(); if (!Ok || !Need(n)) return ""; var s = Encoding.UTF8.GetString(_b.Slice(_o, n)); _o += n; return s; }
  public byte[] Bytes() { var n = (int)U32(); if (!Ok || !Need(n)) return Array.Empty<byte>(); var a = _b.Slice(_o, n).ToArray(); _o += n; return a; }
}

public class CursorWriter {
  readonly System.Collections.Generic.List<byte> _p = new();
  public bool Ok => true;
  public void U8(byte v) => _p.Add(v);
  public void U16(ushort v) { Span<byte> t = stackalloc byte[2]; BinaryPrimitives.WriteUInt16LittleEndian(t, v); _p.Add(t[0]); _p.Add(t[1]); }
  public void U32(uint v) { Span<byte> t = stackalloc byte[4]; BinaryPrimitives.WriteUInt32LittleEndian(t, v); for (int i=0;i<4;i++) _p.Add(t[i]); }
  public void U64(ulong v) { Span<byte> t = stackalloc byte[8]; BinaryPrimitives.WriteUInt64LittleEndian(t, v); for (int i=0;i<8;i++) _p.Add(t[i]); }
  public void I32(int v) => U32(unchecked((uint)v));
  public void Bool(bool v) => U8(v ? (byte)1 : (byte)0);
  public void Str(string v) { var b = Encoding.UTF8.GetBytes(v); U32((uint)b.Length); _p.AddRange(b); }
  public void Bytes(ReadOnlySpan<byte> v) { U32((uint)v.Length); for (int i=0;i<v.Length;i++) _p.Add(v[i]); }
  public byte[] ToArray() => _p.ToArray();
}

public enum LoadState : byte {
  Started = 1,
  Stopped = 2,
}

public enum ResyncForce : byte {
  FromMap = 0,
  FromWalk = 1,
}

public enum Scope : byte {
  Self = 0,
  Subtree = 1,
}

public enum MouseButton : byte {
  Left = 0,
  Middle = 1,
  Right = 2,
}

public enum PromptKind : byte {
  Dialog = 1,
  Permission = 2,
  Download = 3,
}

public enum ValueTag : byte {
  U64 = 0,
  I64 = 1,
  F64 = 2,
  Str = 3,
}

public enum FaultKey : ushort {
  Viewport = 1,
  Host = 2,
  Document = 3,
  Process = 4,
  Stream = 5,
  Node = 6,
  Sheet = 7,
  Rule = 8,
  Request = 9,
  Offset = 10,
  Expected = 11,
  Actual = 12,
  Phase = 13,
  Kind = 14,
  Count = 15,
  Limit = 16,
  Span = 17,
}

public enum FaultCode : ushort {
  FramingLost = 1,
  CeilingExceeded = 2,
  WrongDirection = 3,
  MalformedFields = 4,
  LinkBroken = 5,
  ClockUnavailable = 6,
  ViewportOpenRefused = 20,
  NoSuchViewport = 21,
  NoSuchHost = 22,
  HostGone = 23,
  NoSuchDocument = 24,
  DocumentGone = 25,
  MalformedUrl = 26,
  NavigateRefused = 27,
  ResizeRefused = 28,
  StaleGeneration = 29,
  ProbeDisabled = 30,
  HaltIncomplete = 31,
  CaptureUnavailable = 32,
  StaleFreezeToken = 33,
  ResyncCheckFailed = 40,
  SnapshotTooLarge = 41,
  IdentityExhausted = 42,
  InputUnknownKind = 60,
  InputNoIdentity = 61,
  InputNodeGone = 62,
  InputNotElement = 63,
  InputHalted = 64,
  InputNoTarget = 65,
  AssetNotFound = 80,
  AssetForbidden = 81,
  AssetReadFailed = 82,
  AssetOffsetGap = 83,
  AssetPhaseViolation = 84,
  AssetTooManyStreams = 85,
}

public enum CaptureKind : byte {
  Table = 1,
  Rebuilt = 2,
  Naive = 3,
}

public enum ProbeId : ushort {
  HostTable = 1,
  RangeDigest = 2,
  IdentityMap = 3,
  RegistryState = 4,
  WriterState = 5,
  PendingDirty = 6,
}

public enum MetricId : ushort {
  BuildMicros = 1,
  OpCount = 2,
  TableSize = 3,
  DirtyCount = 4,
  EncodeMicros = 5,
}

public enum TelemetryId : ushort {
  PatchEmitted = 1,
  ResyncRequested = 2,
  ResyncDone = 3,
  ResyncFailed = 4,
  ProducerFault = 5,
  InputAdmitted = 6,
  InputRejected = 7,
}

public struct Extent {
  public int width;
  public int height;
}

public struct KeyStroke {
  public string key;
  public string code;
  public byte mods;
}

public struct Metric {
  public MetricId id;
  public ulong value;
}

public struct FaultDatum {
  public FaultKey key;
  public ValueTag tag;
  public ulong num;
  public string text;
}

public static class OpFreezeAll { public const ushort Code = 0x0F10; }
public struct FreezeAll {
  public uint timeoutMs;
}

public static class OpCaptureState { public const ushort Code = 0x0F11; }
public struct CaptureState {
  public uint token;
  public CaptureKind kind;
}

public static class OpThawAll { public const ushort Code = 0x0F12; }
public struct ThawAll {
  public uint token;
}

public static class OpProbe { public const ushort Code = 0x0F01; }
public struct Probe {
  public ProbeId id;
  public byte[] args;
}

public static class OpShutdown { public const ushort Code = 0x0101; }
public struct Shutdown {
}

public static class OpViewportOpen { public const ushort Code = 0x0102; }
public struct ViewportOpen {
  public Extent extent;
}

public static class OpViewportClose { public const ushort Code = 0x0201; }
public struct ViewportClose {
}

public static class OpViewportResize { public const ushort Code = 0x0202; }
public struct ViewportResize {
  public Extent extent;
}

public static class OpNavigate { public const ushort Code = 0x0301; }
public struct Navigate {
  public string url;
}

public static class OpReload { public const ushort Code = 0x0302; }
public struct Reload {
}

public static class OpStopLoad { public const ushort Code = 0x0303; }
public struct StopLoad {
}

public static class OpHistoryGo { public const ushort Code = 0x0304; }
public struct HistoryGo {
  public int delta;
}

public static class OpHostResize { public const ushort Code = 0x0305; }
public struct HostResize {
  public Extent extent;
}

public static class OpResync { public const ushort Code = 0x0306; }
public struct Resync {
  public ResyncForce force;
  public Scope scope;
}

public static class OpClocksHalt { public const ushort Code = 0x0307; }
public struct ClocksHalt {
  public Scope scope;
}

public static class OpClocksResume { public const ushort Code = 0x0308; }
public struct ClocksResume {
  public Scope scope;
}

public static class OpPromptRespond { public const ushort Code = 0x0309; }
public struct PromptRespond {
  public uint request;
  public byte[] answer;
}

public static class OpFlush { public const ushort Code = 0x0401; }
public struct Flush {
  public uint generation;
}

public static class OpSnapshot { public const ushort Code = 0x0402; }
public struct Snapshot {
  public uint generation;
}

public static class OpInputPointerDown { public const ushort Code = 0x0410; }
public struct InputPointerDown {
  public uint generation;
  public uint node;
  public ushort localX;
  public ushort localY;
  public MouseButton button;
}

public static class OpInputPointerUp { public const ushort Code = 0x0411; }
public struct InputPointerUp {
  public uint generation;
  public uint node;
  public ushort localX;
  public ushort localY;
  public MouseButton button;
}

public static class OpInputKeyDown { public const ushort Code = 0x0412; }
public struct InputKeyDown {
  public KeyStroke stroke;
}

public static class OpInputKeyUp { public const ushort Code = 0x0413; }
public struct InputKeyUp {
  public KeyStroke stroke;
}

public static class OpInputScroll { public const ushort Code = 0x0414; }
public struct InputScroll {
  public uint generation;
  public uint node;
  public ushort fracX;
  public ushort fracY;
}

public static class OpAssetRequest { public const ushort Code = 0x0420; }
public struct AssetRequest {
  public uint generation;
  public uint stream;
  public string url;
}

public static class OpAssetCancel { public const ushort Code = 0x0421; }
public struct AssetCancel {
  public uint stream;
}

public static class OpReady { public const ushort Code = 0x8101; }
public struct Ready {
}

public static class OpHeartbeat { public const ushort Code = 0x8102; }
public struct Heartbeat {
  public ulong monotonicMs;
}

public static class OpViewportOpened { public const ushort Code = 0x8201; }
public struct ViewportOpened {
  public uint rootHost;
}

public static class OpViewportClosed { public const ushort Code = 0x8202; }
public struct ViewportClosed {
}

public static class OpHostAttached { public const ushort Code = 0x8301; }
public struct HostAttached {
  public uint parent;
  public uint viewport;
}

public static class OpHostDetached { public const ushort Code = 0x8302; }
public struct HostDetached {
}

public static class OpDocumentInstalled { public const ushort Code = 0x8303; }
public struct DocumentInstalled {
  public uint generation;
}

public static class OpDocumentDiscarded { public const ushort Code = 0x8304; }
public struct DocumentDiscarded {
  public uint generation;
}

public static class OpNavigated { public const ushort Code = 0x8305; }
public struct Navigated {
  public string url;
}

public static class OpLoadStateChanged { public const ushort Code = 0x8306; }
public struct LoadStateChanged {
  public LoadState state;
}

public static class OpPromptRequested { public const ushort Code = 0x8307; }
public struct PromptRequested {
  public uint request;
  public PromptKind kind;
  public byte[] description;
}

public static class OpPromptAbandoned { public const ushort Code = 0x8308; }
public struct PromptAbandoned {
  public uint request;
}

public static class OpPatch { public const ushort Code = 0x8401; }
public struct Patch {
  public uint generation;
  public uint sequence;
  public ushort flags;
  public uint builtAt;
  public Metric[] metrics;
  public byte[] deltas;
}

public static class OpSnapshotted { public const ushort Code = 0x8402; }
public struct Snapshotted {
  public uint generation;
  public uint sequence;
  public ulong digest;
  public byte[] dump;
}

public static class OpAssetChunk { public const ushort Code = 0x8420; }
public struct AssetChunk {
  public uint stream;
  public ulong offset;
  public byte[] data;
}

public static class OpAssetEnd { public const ushort Code = 0x8421; }
public struct AssetEnd {
  public uint stream;
  public ulong total;
}

public static class OpAssetDenied { public const ushort Code = 0x8422; }
public struct AssetDenied {
  public uint stream;
  public FaultCode code;
}

public static class OpFault { public const ushort Code = 0x8F01; }
public struct Fault {
  public FaultCode code;
  public uint flags;
  public string origin;
  public string message;
  public FaultDatum[] data;
}

public static class OpFreezeResult { public const ushort Code = 0x8F10; }
public struct FreezeResult {
  public uint token;
  public uint frozen;
  public uint expected;
}

public static class OpStateCaptured { public const ushort Code = 0x8F11; }
public struct StateCaptured {
  public uint token;
  public uint host;
  public uint generation;
  public CaptureKind kind;
  public ulong digest;
  public byte[] image;
}

public static class OpProbeResult { public const ushort Code = 0x8F03; }
public struct ProbeResult {
  public ProbeId id;
  public bool enabled;
  public byte[] payload;
}

public static class OpTelemetry { public const ushort Code = 0x8F02; }
public struct Telemetry {
  public TelemetryId id;
  public byte[] payload;
}

public static class Codecs {
  public static void EncodeExtent(CursorWriter w, Extent v) {
    w.I32(v.width);
    w.I32(v.height);
  }
  public static Extent DecodeExtent(ref CursorReader r) {
    var v = new Extent();
    v.width = r.I32();
    v.height = r.I32();
    return v;
  }
  public static void EncodeKeyStroke(CursorWriter w, KeyStroke v) {
    w.Str(v.key);
    w.Str(v.code);
    w.U8(v.mods);
  }
  public static KeyStroke DecodeKeyStroke(ref CursorReader r) {
    var v = new KeyStroke();
    v.key = r.Str();
    v.code = r.Str();
    v.mods = r.U8();
    return v;
  }
  public static void EncodeMetric(CursorWriter w, Metric v) {
    w.U16((ushort)v.id);
    w.U64(v.value);
  }
  public static Metric DecodeMetric(ref CursorReader r) {
    var v = new Metric();
    v.id = (MetricId)r.U16();
    v.value = r.U64();
    return v;
  }
  public static void EncodeFaultDatum(CursorWriter w, FaultDatum v) {
    w.U16((ushort)v.key);
    w.U8((byte)v.tag);
    w.U64(v.num);
    w.Str(v.text);
  }
  public static FaultDatum DecodeFaultDatum(ref CursorReader r) {
    var v = new FaultDatum();
    v.key = (FaultKey)r.U16();
    v.tag = (ValueTag)r.U8();
    v.num = r.U64();
    v.text = r.Str();
    return v;
  }
  public static void EncodeFreezeAll(CursorWriter w, FreezeAll v) {
    w.U32(v.timeoutMs);
  }
  public static FreezeAll DecodeFreezeAll(ref CursorReader r) {
    var v = new FreezeAll();
    v.timeoutMs = r.U32();
    if (!r.Ok) throw new InvalidOperationException("decode FreezeAll");
    return v;
  }
  public static byte[] EncodeFreezeAllBytes(FreezeAll v) { var w = new CursorWriter(); EncodeFreezeAll(w, v); return w.ToArray(); }
  public static FreezeAll DecodeFreezeAllBytes(ReadOnlySpan<byte> b) { var r = new CursorReader(b); return DecodeFreezeAll(ref r); }
  public static void EncodeCaptureState(CursorWriter w, CaptureState v) {
    w.U32(v.token);
    w.U8((byte)v.kind);
  }
  public static CaptureState DecodeCaptureState(ref CursorReader r) {
    var v = new CaptureState();
    v.token = r.U32();
    v.kind = (CaptureKind)r.U8();
    if (!r.Ok) throw new InvalidOperationException("decode CaptureState");
    return v;
  }
  public static byte[] EncodeCaptureStateBytes(CaptureState v) { var w = new CursorWriter(); EncodeCaptureState(w, v); return w.ToArray(); }
  public static CaptureState DecodeCaptureStateBytes(ReadOnlySpan<byte> b) { var r = new CursorReader(b); return DecodeCaptureState(ref r); }
  public static void EncodeThawAll(CursorWriter w, ThawAll v) {
    w.U32(v.token);
  }
  public static ThawAll DecodeThawAll(ref CursorReader r) {
    var v = new ThawAll();
    v.token = r.U32();
    if (!r.Ok) throw new InvalidOperationException("decode ThawAll");
    return v;
  }
  public static byte[] EncodeThawAllBytes(ThawAll v) { var w = new CursorWriter(); EncodeThawAll(w, v); return w.ToArray(); }
  public static ThawAll DecodeThawAllBytes(ReadOnlySpan<byte> b) { var r = new CursorReader(b); return DecodeThawAll(ref r); }
  public static void EncodeProbe(CursorWriter w, Probe v) {
    w.U16((ushort)v.id);
    w.Bytes(v.args);
  }
  public static Probe DecodeProbe(ref CursorReader r) {
    var v = new Probe();
    v.id = (ProbeId)r.U16();
    v.args = Array.Empty<byte>();
    v.args = r.Bytes();
    if (!r.Ok) throw new InvalidOperationException("decode Probe");
    return v;
  }
  public static byte[] EncodeProbeBytes(Probe v) { var w = new CursorWriter(); EncodeProbe(w, v); return w.ToArray(); }
  public static Probe DecodeProbeBytes(ReadOnlySpan<byte> b) { var r = new CursorReader(b); return DecodeProbe(ref r); }
  public static void EncodeShutdown(CursorWriter w, Shutdown v) {
  }
  public static Shutdown DecodeShutdown(ref CursorReader r) {
    var v = new Shutdown();
    if (!r.Ok) throw new InvalidOperationException("decode Shutdown");
    return v;
  }
  public static byte[] EncodeShutdownBytes(Shutdown v) { var w = new CursorWriter(); EncodeShutdown(w, v); return w.ToArray(); }
  public static Shutdown DecodeShutdownBytes(ReadOnlySpan<byte> b) { var r = new CursorReader(b); return DecodeShutdown(ref r); }
  public static void EncodeViewportOpen(CursorWriter w, ViewportOpen v) {
    EncodeExtent(w, v.extent);
  }
  public static ViewportOpen DecodeViewportOpen(ref CursorReader r) {
    var v = new ViewportOpen();
    v.extent = DecodeExtent(ref r);
    if (!r.Ok) throw new InvalidOperationException("decode ViewportOpen");
    return v;
  }
  public static byte[] EncodeViewportOpenBytes(ViewportOpen v) { var w = new CursorWriter(); EncodeViewportOpen(w, v); return w.ToArray(); }
  public static ViewportOpen DecodeViewportOpenBytes(ReadOnlySpan<byte> b) { var r = new CursorReader(b); return DecodeViewportOpen(ref r); }
  public static void EncodeViewportClose(CursorWriter w, ViewportClose v) {
  }
  public static ViewportClose DecodeViewportClose(ref CursorReader r) {
    var v = new ViewportClose();
    if (!r.Ok) throw new InvalidOperationException("decode ViewportClose");
    return v;
  }
  public static byte[] EncodeViewportCloseBytes(ViewportClose v) { var w = new CursorWriter(); EncodeViewportClose(w, v); return w.ToArray(); }
  public static ViewportClose DecodeViewportCloseBytes(ReadOnlySpan<byte> b) { var r = new CursorReader(b); return DecodeViewportClose(ref r); }
  public static void EncodeViewportResize(CursorWriter w, ViewportResize v) {
    EncodeExtent(w, v.extent);
  }
  public static ViewportResize DecodeViewportResize(ref CursorReader r) {
    var v = new ViewportResize();
    v.extent = DecodeExtent(ref r);
    if (!r.Ok) throw new InvalidOperationException("decode ViewportResize");
    return v;
  }
  public static byte[] EncodeViewportResizeBytes(ViewportResize v) { var w = new CursorWriter(); EncodeViewportResize(w, v); return w.ToArray(); }
  public static ViewportResize DecodeViewportResizeBytes(ReadOnlySpan<byte> b) { var r = new CursorReader(b); return DecodeViewportResize(ref r); }
  public static void EncodeNavigate(CursorWriter w, Navigate v) {
    w.Str(v.url);
  }
  public static Navigate DecodeNavigate(ref CursorReader r) {
    var v = new Navigate();
    v.url = "";
    v.url = r.Str();
    if (!r.Ok) throw new InvalidOperationException("decode Navigate");
    return v;
  }
  public static byte[] EncodeNavigateBytes(Navigate v) { var w = new CursorWriter(); EncodeNavigate(w, v); return w.ToArray(); }
  public static Navigate DecodeNavigateBytes(ReadOnlySpan<byte> b) { var r = new CursorReader(b); return DecodeNavigate(ref r); }
  public static void EncodeReload(CursorWriter w, Reload v) {
  }
  public static Reload DecodeReload(ref CursorReader r) {
    var v = new Reload();
    if (!r.Ok) throw new InvalidOperationException("decode Reload");
    return v;
  }
  public static byte[] EncodeReloadBytes(Reload v) { var w = new CursorWriter(); EncodeReload(w, v); return w.ToArray(); }
  public static Reload DecodeReloadBytes(ReadOnlySpan<byte> b) { var r = new CursorReader(b); return DecodeReload(ref r); }
  public static void EncodeStopLoad(CursorWriter w, StopLoad v) {
  }
  public static StopLoad DecodeStopLoad(ref CursorReader r) {
    var v = new StopLoad();
    if (!r.Ok) throw new InvalidOperationException("decode StopLoad");
    return v;
  }
  public static byte[] EncodeStopLoadBytes(StopLoad v) { var w = new CursorWriter(); EncodeStopLoad(w, v); return w.ToArray(); }
  public static StopLoad DecodeStopLoadBytes(ReadOnlySpan<byte> b) { var r = new CursorReader(b); return DecodeStopLoad(ref r); }
  public static void EncodeHistoryGo(CursorWriter w, HistoryGo v) {
    w.I32(v.delta);
  }
  public static HistoryGo DecodeHistoryGo(ref CursorReader r) {
    var v = new HistoryGo();
    v.delta = r.I32();
    if (!r.Ok) throw new InvalidOperationException("decode HistoryGo");
    return v;
  }
  public static byte[] EncodeHistoryGoBytes(HistoryGo v) { var w = new CursorWriter(); EncodeHistoryGo(w, v); return w.ToArray(); }
  public static HistoryGo DecodeHistoryGoBytes(ReadOnlySpan<byte> b) { var r = new CursorReader(b); return DecodeHistoryGo(ref r); }
  public static void EncodeHostResize(CursorWriter w, HostResize v) {
    EncodeExtent(w, v.extent);
  }
  public static HostResize DecodeHostResize(ref CursorReader r) {
    var v = new HostResize();
    v.extent = DecodeExtent(ref r);
    if (!r.Ok) throw new InvalidOperationException("decode HostResize");
    return v;
  }
  public static byte[] EncodeHostResizeBytes(HostResize v) { var w = new CursorWriter(); EncodeHostResize(w, v); return w.ToArray(); }
  public static HostResize DecodeHostResizeBytes(ReadOnlySpan<byte> b) { var r = new CursorReader(b); return DecodeHostResize(ref r); }
  public static void EncodeResync(CursorWriter w, Resync v) {
    w.U8((byte)v.force);
    w.U8((byte)v.scope);
  }
  public static Resync DecodeResync(ref CursorReader r) {
    var v = new Resync();
    v.force = (ResyncForce)r.U8();
    v.scope = (Scope)r.U8();
    if (!r.Ok) throw new InvalidOperationException("decode Resync");
    return v;
  }
  public static byte[] EncodeResyncBytes(Resync v) { var w = new CursorWriter(); EncodeResync(w, v); return w.ToArray(); }
  public static Resync DecodeResyncBytes(ReadOnlySpan<byte> b) { var r = new CursorReader(b); return DecodeResync(ref r); }
  public static void EncodeClocksHalt(CursorWriter w, ClocksHalt v) {
    w.U8((byte)v.scope);
  }
  public static ClocksHalt DecodeClocksHalt(ref CursorReader r) {
    var v = new ClocksHalt();
    v.scope = (Scope)r.U8();
    if (!r.Ok) throw new InvalidOperationException("decode ClocksHalt");
    return v;
  }
  public static byte[] EncodeClocksHaltBytes(ClocksHalt v) { var w = new CursorWriter(); EncodeClocksHalt(w, v); return w.ToArray(); }
  public static ClocksHalt DecodeClocksHaltBytes(ReadOnlySpan<byte> b) { var r = new CursorReader(b); return DecodeClocksHalt(ref r); }
  public static void EncodeClocksResume(CursorWriter w, ClocksResume v) {
    w.U8((byte)v.scope);
  }
  public static ClocksResume DecodeClocksResume(ref CursorReader r) {
    var v = new ClocksResume();
    v.scope = (Scope)r.U8();
    if (!r.Ok) throw new InvalidOperationException("decode ClocksResume");
    return v;
  }
  public static byte[] EncodeClocksResumeBytes(ClocksResume v) { var w = new CursorWriter(); EncodeClocksResume(w, v); return w.ToArray(); }
  public static ClocksResume DecodeClocksResumeBytes(ReadOnlySpan<byte> b) { var r = new CursorReader(b); return DecodeClocksResume(ref r); }
  public static void EncodePromptRespond(CursorWriter w, PromptRespond v) {
    w.U32(v.request);
    w.Bytes(v.answer);
  }
  public static PromptRespond DecodePromptRespond(ref CursorReader r) {
    var v = new PromptRespond();
    v.request = r.U32();
    v.answer = Array.Empty<byte>();
    v.answer = r.Bytes();
    if (!r.Ok) throw new InvalidOperationException("decode PromptRespond");
    return v;
  }
  public static byte[] EncodePromptRespondBytes(PromptRespond v) { var w = new CursorWriter(); EncodePromptRespond(w, v); return w.ToArray(); }
  public static PromptRespond DecodePromptRespondBytes(ReadOnlySpan<byte> b) { var r = new CursorReader(b); return DecodePromptRespond(ref r); }
  public static void EncodeFlush(CursorWriter w, Flush v) {
    w.U32(v.generation);
  }
  public static Flush DecodeFlush(ref CursorReader r) {
    var v = new Flush();
    v.generation = r.U32();
    if (!r.Ok) throw new InvalidOperationException("decode Flush");
    return v;
  }
  public static byte[] EncodeFlushBytes(Flush v) { var w = new CursorWriter(); EncodeFlush(w, v); return w.ToArray(); }
  public static Flush DecodeFlushBytes(ReadOnlySpan<byte> b) { var r = new CursorReader(b); return DecodeFlush(ref r); }
  public static void EncodeSnapshot(CursorWriter w, Snapshot v) {
    w.U32(v.generation);
  }
  public static Snapshot DecodeSnapshot(ref CursorReader r) {
    var v = new Snapshot();
    v.generation = r.U32();
    if (!r.Ok) throw new InvalidOperationException("decode Snapshot");
    return v;
  }
  public static byte[] EncodeSnapshotBytes(Snapshot v) { var w = new CursorWriter(); EncodeSnapshot(w, v); return w.ToArray(); }
  public static Snapshot DecodeSnapshotBytes(ReadOnlySpan<byte> b) { var r = new CursorReader(b); return DecodeSnapshot(ref r); }
  public static void EncodeInputPointerDown(CursorWriter w, InputPointerDown v) {
    w.U32(v.generation);
    w.U32(v.node);
    w.U16(v.localX);
    w.U16(v.localY);
    w.U8((byte)v.button);
  }
  public static InputPointerDown DecodeInputPointerDown(ref CursorReader r) {
    var v = new InputPointerDown();
    v.generation = r.U32();
    v.node = r.U32();
    v.localX = r.U16();
    v.localY = r.U16();
    v.button = (MouseButton)r.U8();
    if (!r.Ok) throw new InvalidOperationException("decode InputPointerDown");
    return v;
  }
  public static byte[] EncodeInputPointerDownBytes(InputPointerDown v) { var w = new CursorWriter(); EncodeInputPointerDown(w, v); return w.ToArray(); }
  public static InputPointerDown DecodeInputPointerDownBytes(ReadOnlySpan<byte> b) { var r = new CursorReader(b); return DecodeInputPointerDown(ref r); }
  public static void EncodeInputPointerUp(CursorWriter w, InputPointerUp v) {
    w.U32(v.generation);
    w.U32(v.node);
    w.U16(v.localX);
    w.U16(v.localY);
    w.U8((byte)v.button);
  }
  public static InputPointerUp DecodeInputPointerUp(ref CursorReader r) {
    var v = new InputPointerUp();
    v.generation = r.U32();
    v.node = r.U32();
    v.localX = r.U16();
    v.localY = r.U16();
    v.button = (MouseButton)r.U8();
    if (!r.Ok) throw new InvalidOperationException("decode InputPointerUp");
    return v;
  }
  public static byte[] EncodeInputPointerUpBytes(InputPointerUp v) { var w = new CursorWriter(); EncodeInputPointerUp(w, v); return w.ToArray(); }
  public static InputPointerUp DecodeInputPointerUpBytes(ReadOnlySpan<byte> b) { var r = new CursorReader(b); return DecodeInputPointerUp(ref r); }
  public static void EncodeInputKeyDown(CursorWriter w, InputKeyDown v) {
    EncodeKeyStroke(w, v.stroke);
  }
  public static InputKeyDown DecodeInputKeyDown(ref CursorReader r) {
    var v = new InputKeyDown();
    v.stroke = DecodeKeyStroke(ref r);
    if (!r.Ok) throw new InvalidOperationException("decode InputKeyDown");
    return v;
  }
  public static byte[] EncodeInputKeyDownBytes(InputKeyDown v) { var w = new CursorWriter(); EncodeInputKeyDown(w, v); return w.ToArray(); }
  public static InputKeyDown DecodeInputKeyDownBytes(ReadOnlySpan<byte> b) { var r = new CursorReader(b); return DecodeInputKeyDown(ref r); }
  public static void EncodeInputKeyUp(CursorWriter w, InputKeyUp v) {
    EncodeKeyStroke(w, v.stroke);
  }
  public static InputKeyUp DecodeInputKeyUp(ref CursorReader r) {
    var v = new InputKeyUp();
    v.stroke = DecodeKeyStroke(ref r);
    if (!r.Ok) throw new InvalidOperationException("decode InputKeyUp");
    return v;
  }
  public static byte[] EncodeInputKeyUpBytes(InputKeyUp v) { var w = new CursorWriter(); EncodeInputKeyUp(w, v); return w.ToArray(); }
  public static InputKeyUp DecodeInputKeyUpBytes(ReadOnlySpan<byte> b) { var r = new CursorReader(b); return DecodeInputKeyUp(ref r); }
  public static void EncodeInputScroll(CursorWriter w, InputScroll v) {
    w.U32(v.generation);
    w.U32(v.node);
    w.U16(v.fracX);
    w.U16(v.fracY);
  }
  public static InputScroll DecodeInputScroll(ref CursorReader r) {
    var v = new InputScroll();
    v.generation = r.U32();
    v.node = r.U32();
    v.fracX = r.U16();
    v.fracY = r.U16();
    if (!r.Ok) throw new InvalidOperationException("decode InputScroll");
    return v;
  }
  public static byte[] EncodeInputScrollBytes(InputScroll v) { var w = new CursorWriter(); EncodeInputScroll(w, v); return w.ToArray(); }
  public static InputScroll DecodeInputScrollBytes(ReadOnlySpan<byte> b) { var r = new CursorReader(b); return DecodeInputScroll(ref r); }
  public static void EncodeAssetRequest(CursorWriter w, AssetRequest v) {
    w.U32(v.generation);
    w.U32(v.stream);
    w.Str(v.url);
  }
  public static AssetRequest DecodeAssetRequest(ref CursorReader r) {
    var v = new AssetRequest();
    v.generation = r.U32();
    v.stream = r.U32();
    v.url = "";
    v.url = r.Str();
    if (!r.Ok) throw new InvalidOperationException("decode AssetRequest");
    return v;
  }
  public static byte[] EncodeAssetRequestBytes(AssetRequest v) { var w = new CursorWriter(); EncodeAssetRequest(w, v); return w.ToArray(); }
  public static AssetRequest DecodeAssetRequestBytes(ReadOnlySpan<byte> b) { var r = new CursorReader(b); return DecodeAssetRequest(ref r); }
  public static void EncodeAssetCancel(CursorWriter w, AssetCancel v) {
    w.U32(v.stream);
  }
  public static AssetCancel DecodeAssetCancel(ref CursorReader r) {
    var v = new AssetCancel();
    v.stream = r.U32();
    if (!r.Ok) throw new InvalidOperationException("decode AssetCancel");
    return v;
  }
  public static byte[] EncodeAssetCancelBytes(AssetCancel v) { var w = new CursorWriter(); EncodeAssetCancel(w, v); return w.ToArray(); }
  public static AssetCancel DecodeAssetCancelBytes(ReadOnlySpan<byte> b) { var r = new CursorReader(b); return DecodeAssetCancel(ref r); }
  public static void EncodeReady(CursorWriter w, Ready v) {
  }
  public static Ready DecodeReady(ref CursorReader r) {
    var v = new Ready();
    if (!r.Ok) throw new InvalidOperationException("decode Ready");
    return v;
  }
  public static byte[] EncodeReadyBytes(Ready v) { var w = new CursorWriter(); EncodeReady(w, v); return w.ToArray(); }
  public static Ready DecodeReadyBytes(ReadOnlySpan<byte> b) { var r = new CursorReader(b); return DecodeReady(ref r); }
  public static void EncodeHeartbeat(CursorWriter w, Heartbeat v) {
    w.U64(v.monotonicMs);
  }
  public static Heartbeat DecodeHeartbeat(ref CursorReader r) {
    var v = new Heartbeat();
    v.monotonicMs = r.U64();
    if (!r.Ok) throw new InvalidOperationException("decode Heartbeat");
    return v;
  }
  public static byte[] EncodeHeartbeatBytes(Heartbeat v) { var w = new CursorWriter(); EncodeHeartbeat(w, v); return w.ToArray(); }
  public static Heartbeat DecodeHeartbeatBytes(ReadOnlySpan<byte> b) { var r = new CursorReader(b); return DecodeHeartbeat(ref r); }
  public static void EncodeViewportOpened(CursorWriter w, ViewportOpened v) {
    w.U32(v.rootHost);
  }
  public static ViewportOpened DecodeViewportOpened(ref CursorReader r) {
    var v = new ViewportOpened();
    v.rootHost = r.U32();
    if (!r.Ok) throw new InvalidOperationException("decode ViewportOpened");
    return v;
  }
  public static byte[] EncodeViewportOpenedBytes(ViewportOpened v) { var w = new CursorWriter(); EncodeViewportOpened(w, v); return w.ToArray(); }
  public static ViewportOpened DecodeViewportOpenedBytes(ReadOnlySpan<byte> b) { var r = new CursorReader(b); return DecodeViewportOpened(ref r); }
  public static void EncodeViewportClosed(CursorWriter w, ViewportClosed v) {
  }
  public static ViewportClosed DecodeViewportClosed(ref CursorReader r) {
    var v = new ViewportClosed();
    if (!r.Ok) throw new InvalidOperationException("decode ViewportClosed");
    return v;
  }
  public static byte[] EncodeViewportClosedBytes(ViewportClosed v) { var w = new CursorWriter(); EncodeViewportClosed(w, v); return w.ToArray(); }
  public static ViewportClosed DecodeViewportClosedBytes(ReadOnlySpan<byte> b) { var r = new CursorReader(b); return DecodeViewportClosed(ref r); }
  public static void EncodeHostAttached(CursorWriter w, HostAttached v) {
    w.U32(v.parent);
    w.U32(v.viewport);
  }
  public static HostAttached DecodeHostAttached(ref CursorReader r) {
    var v = new HostAttached();
    v.parent = r.U32();
    v.viewport = r.U32();
    if (!r.Ok) throw new InvalidOperationException("decode HostAttached");
    return v;
  }
  public static byte[] EncodeHostAttachedBytes(HostAttached v) { var w = new CursorWriter(); EncodeHostAttached(w, v); return w.ToArray(); }
  public static HostAttached DecodeHostAttachedBytes(ReadOnlySpan<byte> b) { var r = new CursorReader(b); return DecodeHostAttached(ref r); }
  public static void EncodeHostDetached(CursorWriter w, HostDetached v) {
  }
  public static HostDetached DecodeHostDetached(ref CursorReader r) {
    var v = new HostDetached();
    if (!r.Ok) throw new InvalidOperationException("decode HostDetached");
    return v;
  }
  public static byte[] EncodeHostDetachedBytes(HostDetached v) { var w = new CursorWriter(); EncodeHostDetached(w, v); return w.ToArray(); }
  public static HostDetached DecodeHostDetachedBytes(ReadOnlySpan<byte> b) { var r = new CursorReader(b); return DecodeHostDetached(ref r); }
  public static void EncodeDocumentInstalled(CursorWriter w, DocumentInstalled v) {
    w.U32(v.generation);
  }
  public static DocumentInstalled DecodeDocumentInstalled(ref CursorReader r) {
    var v = new DocumentInstalled();
    v.generation = r.U32();
    if (!r.Ok) throw new InvalidOperationException("decode DocumentInstalled");
    return v;
  }
  public static byte[] EncodeDocumentInstalledBytes(DocumentInstalled v) { var w = new CursorWriter(); EncodeDocumentInstalled(w, v); return w.ToArray(); }
  public static DocumentInstalled DecodeDocumentInstalledBytes(ReadOnlySpan<byte> b) { var r = new CursorReader(b); return DecodeDocumentInstalled(ref r); }
  public static void EncodeDocumentDiscarded(CursorWriter w, DocumentDiscarded v) {
    w.U32(v.generation);
  }
  public static DocumentDiscarded DecodeDocumentDiscarded(ref CursorReader r) {
    var v = new DocumentDiscarded();
    v.generation = r.U32();
    if (!r.Ok) throw new InvalidOperationException("decode DocumentDiscarded");
    return v;
  }
  public static byte[] EncodeDocumentDiscardedBytes(DocumentDiscarded v) { var w = new CursorWriter(); EncodeDocumentDiscarded(w, v); return w.ToArray(); }
  public static DocumentDiscarded DecodeDocumentDiscardedBytes(ReadOnlySpan<byte> b) { var r = new CursorReader(b); return DecodeDocumentDiscarded(ref r); }
  public static void EncodeNavigated(CursorWriter w, Navigated v) {
    w.Str(v.url);
  }
  public static Navigated DecodeNavigated(ref CursorReader r) {
    var v = new Navigated();
    v.url = "";
    v.url = r.Str();
    if (!r.Ok) throw new InvalidOperationException("decode Navigated");
    return v;
  }
  public static byte[] EncodeNavigatedBytes(Navigated v) { var w = new CursorWriter(); EncodeNavigated(w, v); return w.ToArray(); }
  public static Navigated DecodeNavigatedBytes(ReadOnlySpan<byte> b) { var r = new CursorReader(b); return DecodeNavigated(ref r); }
  public static void EncodeLoadStateChanged(CursorWriter w, LoadStateChanged v) {
    w.U8((byte)v.state);
  }
  public static LoadStateChanged DecodeLoadStateChanged(ref CursorReader r) {
    var v = new LoadStateChanged();
    v.state = (LoadState)r.U8();
    if (!r.Ok) throw new InvalidOperationException("decode LoadStateChanged");
    return v;
  }
  public static byte[] EncodeLoadStateChangedBytes(LoadStateChanged v) { var w = new CursorWriter(); EncodeLoadStateChanged(w, v); return w.ToArray(); }
  public static LoadStateChanged DecodeLoadStateChangedBytes(ReadOnlySpan<byte> b) { var r = new CursorReader(b); return DecodeLoadStateChanged(ref r); }
  public static void EncodePromptRequested(CursorWriter w, PromptRequested v) {
    w.U32(v.request);
    w.U8((byte)v.kind);
    w.Bytes(v.description);
  }
  public static PromptRequested DecodePromptRequested(ref CursorReader r) {
    var v = new PromptRequested();
    v.request = r.U32();
    v.kind = (PromptKind)r.U8();
    v.description = Array.Empty<byte>();
    v.description = r.Bytes();
    if (!r.Ok) throw new InvalidOperationException("decode PromptRequested");
    return v;
  }
  public static byte[] EncodePromptRequestedBytes(PromptRequested v) { var w = new CursorWriter(); EncodePromptRequested(w, v); return w.ToArray(); }
  public static PromptRequested DecodePromptRequestedBytes(ReadOnlySpan<byte> b) { var r = new CursorReader(b); return DecodePromptRequested(ref r); }
  public static void EncodePromptAbandoned(CursorWriter w, PromptAbandoned v) {
    w.U32(v.request);
  }
  public static PromptAbandoned DecodePromptAbandoned(ref CursorReader r) {
    var v = new PromptAbandoned();
    v.request = r.U32();
    if (!r.Ok) throw new InvalidOperationException("decode PromptAbandoned");
    return v;
  }
  public static byte[] EncodePromptAbandonedBytes(PromptAbandoned v) { var w = new CursorWriter(); EncodePromptAbandoned(w, v); return w.ToArray(); }
  public static PromptAbandoned DecodePromptAbandonedBytes(ReadOnlySpan<byte> b) { var r = new CursorReader(b); return DecodePromptAbandoned(ref r); }
  public static void EncodePatch(CursorWriter w, Patch v) {
    w.U32(v.generation);
    w.U32(v.sequence);
    w.U16(v.flags);
    w.U32(v.builtAt);
    w.U8((byte)v.metrics.Length); foreach (var _it in v.metrics) { EncodeMetric(w, _it); }
    w.Bytes(v.deltas);
  }
  public static Patch DecodePatch(ref CursorReader r) {
    var v = new Patch();
    v.generation = r.U32();
    v.sequence = r.U32();
    v.flags = r.U16();
    v.builtAt = r.U32();
    v.metrics = Array.Empty<Metric>();
    { var n = r.U8(); v.metrics = new Metric[n]; for (int i=0;i<n;i++) { v.metrics[i] = DecodeMetric(ref r); } }
    v.deltas = Array.Empty<byte>();
    v.deltas = r.Bytes();
    if (!r.Ok) throw new InvalidOperationException("decode Patch");
    return v;
  }
  public static byte[] EncodePatchBytes(Patch v) { var w = new CursorWriter(); EncodePatch(w, v); return w.ToArray(); }
  public static Patch DecodePatchBytes(ReadOnlySpan<byte> b) { var r = new CursorReader(b); return DecodePatch(ref r); }
  public static void EncodeSnapshotted(CursorWriter w, Snapshotted v) {
    w.U32(v.generation);
    w.U32(v.sequence);
    w.U64(v.digest);
    w.Bytes(v.dump);
  }
  public static Snapshotted DecodeSnapshotted(ref CursorReader r) {
    var v = new Snapshotted();
    v.generation = r.U32();
    v.sequence = r.U32();
    v.digest = r.U64();
    v.dump = Array.Empty<byte>();
    v.dump = r.Bytes();
    if (!r.Ok) throw new InvalidOperationException("decode Snapshotted");
    return v;
  }
  public static byte[] EncodeSnapshottedBytes(Snapshotted v) { var w = new CursorWriter(); EncodeSnapshotted(w, v); return w.ToArray(); }
  public static Snapshotted DecodeSnapshottedBytes(ReadOnlySpan<byte> b) { var r = new CursorReader(b); return DecodeSnapshotted(ref r); }
  public static void EncodeAssetChunk(CursorWriter w, AssetChunk v) {
    w.U32(v.stream);
    w.U64(v.offset);
    w.Bytes(v.data);
  }
  public static AssetChunk DecodeAssetChunk(ref CursorReader r) {
    var v = new AssetChunk();
    v.stream = r.U32();
    v.offset = r.U64();
    v.data = Array.Empty<byte>();
    v.data = r.Bytes();
    if (!r.Ok) throw new InvalidOperationException("decode AssetChunk");
    return v;
  }
  public static byte[] EncodeAssetChunkBytes(AssetChunk v) { var w = new CursorWriter(); EncodeAssetChunk(w, v); return w.ToArray(); }
  public static AssetChunk DecodeAssetChunkBytes(ReadOnlySpan<byte> b) { var r = new CursorReader(b); return DecodeAssetChunk(ref r); }
  public static void EncodeAssetEnd(CursorWriter w, AssetEnd v) {
    w.U32(v.stream);
    w.U64(v.total);
  }
  public static AssetEnd DecodeAssetEnd(ref CursorReader r) {
    var v = new AssetEnd();
    v.stream = r.U32();
    v.total = r.U64();
    if (!r.Ok) throw new InvalidOperationException("decode AssetEnd");
    return v;
  }
  public static byte[] EncodeAssetEndBytes(AssetEnd v) { var w = new CursorWriter(); EncodeAssetEnd(w, v); return w.ToArray(); }
  public static AssetEnd DecodeAssetEndBytes(ReadOnlySpan<byte> b) { var r = new CursorReader(b); return DecodeAssetEnd(ref r); }
  public static void EncodeAssetDenied(CursorWriter w, AssetDenied v) {
    w.U32(v.stream);
    w.U16((ushort)v.code);
  }
  public static AssetDenied DecodeAssetDenied(ref CursorReader r) {
    var v = new AssetDenied();
    v.stream = r.U32();
    v.code = (FaultCode)r.U16();
    if (!r.Ok) throw new InvalidOperationException("decode AssetDenied");
    return v;
  }
  public static byte[] EncodeAssetDeniedBytes(AssetDenied v) { var w = new CursorWriter(); EncodeAssetDenied(w, v); return w.ToArray(); }
  public static AssetDenied DecodeAssetDeniedBytes(ReadOnlySpan<byte> b) { var r = new CursorReader(b); return DecodeAssetDenied(ref r); }
  public static void EncodeFault(CursorWriter w, Fault v) {
    w.U16((ushort)v.code);
    w.U32(v.flags);
    w.Str(v.origin);
    w.Str(v.message);
    w.U8((byte)v.data.Length); foreach (var _it in v.data) { EncodeFaultDatum(w, _it); }
  }
  public static Fault DecodeFault(ref CursorReader r) {
    var v = new Fault();
    v.code = (FaultCode)r.U16();
    v.flags = r.U32();
    v.origin = "";
    v.origin = r.Str();
    v.message = "";
    v.message = r.Str();
    v.data = Array.Empty<FaultDatum>();
    { var n = r.U8(); v.data = new FaultDatum[n]; for (int i=0;i<n;i++) { v.data[i] = DecodeFaultDatum(ref r); } }
    if (!r.Ok) throw new InvalidOperationException("decode Fault");
    return v;
  }
  public static byte[] EncodeFaultBytes(Fault v) { var w = new CursorWriter(); EncodeFault(w, v); return w.ToArray(); }
  public static Fault DecodeFaultBytes(ReadOnlySpan<byte> b) { var r = new CursorReader(b); return DecodeFault(ref r); }
  public static void EncodeFreezeResult(CursorWriter w, FreezeResult v) {
    w.U32(v.token);
    w.U32(v.frozen);
    w.U32(v.expected);
  }
  public static FreezeResult DecodeFreezeResult(ref CursorReader r) {
    var v = new FreezeResult();
    v.token = r.U32();
    v.frozen = r.U32();
    v.expected = r.U32();
    if (!r.Ok) throw new InvalidOperationException("decode FreezeResult");
    return v;
  }
  public static byte[] EncodeFreezeResultBytes(FreezeResult v) { var w = new CursorWriter(); EncodeFreezeResult(w, v); return w.ToArray(); }
  public static FreezeResult DecodeFreezeResultBytes(ReadOnlySpan<byte> b) { var r = new CursorReader(b); return DecodeFreezeResult(ref r); }
  public static void EncodeStateCaptured(CursorWriter w, StateCaptured v) {
    w.U32(v.token);
    w.U32(v.host);
    w.U32(v.generation);
    w.U8((byte)v.kind);
    w.U64(v.digest);
    w.Bytes(v.image);
  }
  public static StateCaptured DecodeStateCaptured(ref CursorReader r) {
    var v = new StateCaptured();
    v.token = r.U32();
    v.host = r.U32();
    v.generation = r.U32();
    v.kind = (CaptureKind)r.U8();
    v.digest = r.U64();
    v.image = Array.Empty<byte>();
    v.image = r.Bytes();
    if (!r.Ok) throw new InvalidOperationException("decode StateCaptured");
    return v;
  }
  public static byte[] EncodeStateCapturedBytes(StateCaptured v) { var w = new CursorWriter(); EncodeStateCaptured(w, v); return w.ToArray(); }
  public static StateCaptured DecodeStateCapturedBytes(ReadOnlySpan<byte> b) { var r = new CursorReader(b); return DecodeStateCaptured(ref r); }
  public static void EncodeProbeResult(CursorWriter w, ProbeResult v) {
    w.U16((ushort)v.id);
    w.Bool(v.enabled);
    w.Bytes(v.payload);
  }
  public static ProbeResult DecodeProbeResult(ref CursorReader r) {
    var v = new ProbeResult();
    v.id = (ProbeId)r.U16();
    v.enabled = r.Bool();
    v.payload = Array.Empty<byte>();
    v.payload = r.Bytes();
    if (!r.Ok) throw new InvalidOperationException("decode ProbeResult");
    return v;
  }
  public static byte[] EncodeProbeResultBytes(ProbeResult v) { var w = new CursorWriter(); EncodeProbeResult(w, v); return w.ToArray(); }
  public static ProbeResult DecodeProbeResultBytes(ReadOnlySpan<byte> b) { var r = new CursorReader(b); return DecodeProbeResult(ref r); }
  public static void EncodeTelemetry(CursorWriter w, Telemetry v) {
    w.U16((ushort)v.id);
    w.Bytes(v.payload);
  }
  public static Telemetry DecodeTelemetry(ref CursorReader r) {
    var v = new Telemetry();
    v.id = (TelemetryId)r.U16();
    v.payload = Array.Empty<byte>();
    v.payload = r.Bytes();
    if (!r.Ok) throw new InvalidOperationException("decode Telemetry");
    return v;
  }
  public static byte[] EncodeTelemetryBytes(Telemetry v) { var w = new CursorWriter(); EncodeTelemetry(w, v); return w.ToArray(); }
  public static Telemetry DecodeTelemetryBytes(ReadOnlySpan<byte> b) { var r = new CursorReader(b); return DecodeTelemetry(ref r); }
}