/** Linux EV_KEY codes used by the OS input backend. */
export const KEY = {
  RESERVED: 0,
  ESC: 1,
  '1': 2,
  '2': 3,
  '3': 4,
  '4': 5,
  '5': 6,
  '6': 7,
  '7': 8,
  '8': 9,
  '9': 10,
  '0': 11,
  MINUS: 12,
  EQUAL: 13,
  BACKSPACE: 14,
  TAB: 15,
  Q: 16,
  W: 17,
  E: 18,
  R: 19,
  T: 20,
  Y: 21,
  U: 22,
  I: 23,
  O: 24,
  P: 25,
  LEFTBRACE: 26,
  RIGHTBRACE: 27,
  ENTER: 28,
  LEFTCTRL: 29,
  A: 30,
  S: 31,
  D: 32,
  F: 33,
  G: 34,
  H: 35,
  J: 36,
  K: 37,
  L: 38,
  SEMICOLON: 39,
  APOSTROPHE: 40,
  GRAVE: 41,
  LEFTSHIFT: 42,
  BACKSLASH: 43,
  Z: 44,
  X: 45,
  C: 46,
  V: 47,
  B: 48,
  N: 49,
  M: 50,
  COMMA: 51,
  DOT: 52,
  SLASH: 53,
  RIGHTSHIFT: 54,
  LEFTALT: 56,
  SPACE: 57,
  CAPSLOCK: 58,
  F1: 59,
  F2: 60,
  F3: 61,
  F4: 62,
  F5: 63,
  F6: 64,
  F7: 65,
  F8: 66,
  F9: 67,
  F10: 68,
  F11: 87,
  F12: 88,
  RIGHTCTRL: 97,
  RIGHTALT: 100,
  HOME: 102,
  UP: 103,
  PAGEUP: 104,
  LEFT: 105,
  RIGHT: 106,
  END: 107,
  DOWN: 108,
  PAGEDOWN: 109,
  INSERT: 110,
  DELETE: 111,
  META: 125,
} as const;

const PLAYWRIGHT_TO_EV: Record<string, number> = {
  Backspace: KEY.BACKSPACE,
  Tab: KEY.TAB,
  Enter: KEY.ENTER,
  Escape: KEY.ESC,
  Space: KEY.SPACE,
  ' ': KEY.SPACE,
  ArrowLeft: KEY.LEFT,
  ArrowUp: KEY.UP,
  ArrowRight: KEY.RIGHT,
  ArrowDown: KEY.DOWN,
  Delete: KEY.DELETE,
  Home: KEY.HOME,
  End: KEY.END,
  PageUp: KEY.PAGEUP,
  PageDown: KEY.PAGEDOWN,
  Insert: KEY.INSERT,
  Shift: KEY.LEFTSHIFT,
  Control: KEY.LEFTCTRL,
  Alt: KEY.LEFTALT,
  Meta: KEY.META,
  CapsLock: KEY.CAPSLOCK,
  F1: KEY.F1,
  F2: KEY.F2,
  F3: KEY.F3,
  F4: KEY.F4,
  F5: KEY.F5,
  F6: KEY.F6,
  F7: KEY.F7,
  F8: KEY.F8,
  F9: KEY.F9,
  F10: KEY.F10,
  F11: KEY.F11,
  F12: KEY.F12,
};

const CHAR_TO_EV: Record<string, { code: number; shift?: boolean }> = {
  a: { code: KEY.A },
  b: { code: KEY.B },
  c: { code: KEY.C },
  d: { code: KEY.D },
  e: { code: KEY.E },
  f: { code: KEY.F },
  g: { code: KEY.G },
  h: { code: KEY.H },
  i: { code: KEY.I },
  j: { code: KEY.J },
  k: { code: KEY.K },
  l: { code: KEY.L },
  m: { code: KEY.M },
  n: { code: KEY.N },
  o: { code: KEY.O },
  p: { code: KEY.P },
  q: { code: KEY.Q },
  r: { code: KEY.R },
  s: { code: KEY.S },
  t: { code: KEY.T },
  u: { code: KEY.U },
  v: { code: KEY.V },
  w: { code: KEY.W },
  x: { code: KEY.X },
  y: { code: KEY.Y },
  z: { code: KEY.Z },
  A: { code: KEY.A, shift: true },
  B: { code: KEY.B, shift: true },
  C: { code: KEY.C, shift: true },
  D: { code: KEY.D, shift: true },
  E: { code: KEY.E, shift: true },
  F: { code: KEY.F, shift: true },
  G: { code: KEY.G, shift: true },
  H: { code: KEY.H, shift: true },
  I: { code: KEY.I, shift: true },
  J: { code: KEY.J, shift: true },
  K: { code: KEY.K, shift: true },
  L: { code: KEY.L, shift: true },
  M: { code: KEY.M, shift: true },
  N: { code: KEY.N, shift: true },
  O: { code: KEY.O, shift: true },
  P: { code: KEY.P, shift: true },
  Q: { code: KEY.Q, shift: true },
  R: { code: KEY.R, shift: true },
  S: { code: KEY.S, shift: true },
  T: { code: KEY.T, shift: true },
  U: { code: KEY.U, shift: true },
  V: { code: KEY.V, shift: true },
  W: { code: KEY.W, shift: true },
  X: { code: KEY.X, shift: true },
  Y: { code: KEY.Y, shift: true },
  Z: { code: KEY.Z, shift: true },
  '0': { code: KEY['0'] },
  '1': { code: KEY['1'] },
  '2': { code: KEY['2'] },
  '3': { code: KEY['3'] },
  '4': { code: KEY['4'] },
  '5': { code: KEY['5'] },
  '6': { code: KEY['6'] },
  '7': { code: KEY['7'] },
  '8': { code: KEY['8'] },
  '9': { code: KEY['9'] },
  ' ': { code: KEY.SPACE },
  '-': { code: KEY.MINUS },
  '=': { code: KEY.EQUAL },
  '[': { code: KEY.LEFTBRACE },
  ']': { code: KEY.RIGHTBRACE },
  '\\': { code: KEY.BACKSLASH },
  ';': { code: KEY.SEMICOLON },
  "'": { code: KEY.APOSTROPHE },
  '`': { code: KEY.GRAVE },
  ',': { code: KEY.COMMA },
  '.': { code: KEY.DOT },
  '/': { code: KEY.SLASH },
  _: { code: KEY.MINUS, shift: true },
  '+': { code: KEY.EQUAL, shift: true },
  '{': { code: KEY.LEFTBRACE, shift: true },
  '}': { code: KEY.RIGHTBRACE, shift: true },
  '|': { code: KEY.BACKSLASH, shift: true },
  ':': { code: KEY.SEMICOLON, shift: true },
  '"': { code: KEY.APOSTROPHE, shift: true },
  '~': { code: KEY.GRAVE, shift: true },
  '<': { code: KEY.COMMA, shift: true },
  '>': { code: KEY.DOT, shift: true },
  '?': { code: KEY.SLASH, shift: true },
  '!': { code: KEY['1'], shift: true },
  '@': { code: KEY['2'], shift: true },
  '#': { code: KEY['3'], shift: true },
  $: { code: KEY['4'], shift: true },
  '%': { code: KEY['5'], shift: true },
  '^': { code: KEY['6'], shift: true },
  '&': { code: KEY['7'], shift: true },
  '*': { code: KEY['8'], shift: true },
  '(': { code: KEY['9'], shift: true },
  ')': { code: KEY['0'], shift: true },
};

export type KeyStroke = { code: number; shift?: boolean };

/** Resolve a Playwright-style key name or single printable char to EV_KEY stroke(s). */
export function resolveKeyStroke(key: string): KeyStroke | null {
  if (!key) return null;
  const named = PLAYWRIGHT_TO_EV[key];
  if (named !== undefined) return { code: named };
  if (key.length === 1) {
    return CHAR_TO_EV[key] ?? null;
  }
  return null;
}

/** Keys that should be enabled on the virtual keyboard device. */
export function allKeyboardKeyCodes(): number[] {
  const set = new Set<number>();
  for (const v of Object.values(PLAYWRIGHT_TO_EV)) set.add(v);
  for (const v of Object.values(CHAR_TO_EV)) set.add(v.code);
  set.add(KEY.LEFTSHIFT);
  set.add(KEY.RIGHTSHIFT);
  set.add(KEY.LEFTCTRL);
  set.add(KEY.RIGHTCTRL);
  set.add(KEY.LEFTALT);
  set.add(KEY.RIGHTALT);
  return [...set];
}
