<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Speculum.Supervisor</RootNamespace>
    <AssemblyName>Speculum.Gecko.Abi</AssemblyName>
    <IsAotCompatible>true</IsAotCompatible>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\..\..\wire-clients\cs\SpeculumWire.gen.cs" Link="SpeculumWire.gen.cs" />
  </ItemGroup>

</Project>
