// GENERATED by wiregen — DO NOT EDIT
// schema_sha256=019b629d0cc8374708a62af3177a1f22d06dd0b817a22a32db6dd34a61137142
export const SCHEMA_SHA256 = "019b629d0cc8374708a62af3177a1f22d06dd0b817a22a32db6dd34a61137142";
export const MESSAGE_COUNT = 48;

export class CursorReader {
  private view: DataView;
  private o = 0;
  private _ok = true;
  constructor(buf: ArrayBuffer | Uint8Array) {
    const u = buf instanceof Uint8Array ? buf : new Uint8Array(buf);
    this.view = new DataView(u.buffer, u.byteOffset, u.byteLength);
  }
  ok() { return this._ok; }
  private need(n: number) { if (this.o + n > this.view.byteLength) this._ok = false; return this._ok; }
  u8() { if (!this.need(1)) return 0; const v = this.view.getUint8(this.o); this.o += 1; return v; }
  u16() { if (!this.need(2)) return 0; const v = this.view.getUint16(this.o, true); this.o += 2; return v; }
  u32() { if (!this.need(4)) return 0; const v = this.view.getUint32(this.o, true); this.o += 4; return v; }
  u64() { if (!this.need(8)) return 0n; const lo = this.view.getUint32(this.o, true); const hi = this.view.getUint32(this.o+4, true); this.o += 8; return BigInt(lo) + (BigInt(hi) << 32n); }
  i32() { if (!this.need(4)) return 0; const v = this.view.getInt32(this.o, true); this.o += 4; return v; }
  bool() { return this.u8() !== 0; }
  str() { const n = this.u32(); if (!this._ok || !this.need(n)) return ''; const bytes = new Uint8Array(this.view.buffer, this.view.byteOffset + this.o, n); this.o += n; return new TextDecoder().decode(bytes); }
  bytes() { const n = this.u32(); if (!this._ok || !this.need(n)) return new Uint8Array(); const bytes = new Uint8Array(this.view.buffer, this.view.byteOffset + this.o, n); this.o += n; return bytes.slice(); }
}

export class CursorWriter {
  private parts: number[] = [];
  private _ok = true;
  ok() { return this._ok; }
  u8(v: number) { this.parts.push(v & 0xff); }
  u16(v: number) { this.parts.push(v & 0xff, (v >>> 8) & 0xff); }
  u32(v: number) { this.parts.push(v & 0xff, (v >>> 8) & 0xff, (v >>> 16) & 0xff, (v >>> 24) & 0xff); }
  u64(v: bigint) { const lo = Number(v & 0xffffffffn); const hi = Number((v >> 32n) & 0xffffffffn); this.u32(lo); this.u32(hi); }
  i32(v: number) { this.u32(v >>> 0); }
  bool(v: boolean) { this.u8(v ? 1 : 0); }
  str(v: string) { const b = new TextEncoder().encode(v); this.u32(b.length); for (const x of b) this.parts.push(x); }
  bytes(v: Uint8Array) { this.u32(v.length); for (const x of v) this.parts.push(x); }
  toUint8Array() { return Uint8Array.from(this.parts); }
}

export enum LoadState {
  Started = 1,
  Stopped = 2,
}

export enum ResyncForce {
  FromMap = 0,
  FromWalk = 1,
}

export enum Scope {
  Self = 0,
  Subtree = 1,
}

export enum MouseButton {
  Left = 0,
  Middle = 1,
  Right = 2,
}

export enum PromptKind {
  Dialog = 1,
  Permission = 2,
  Download = 3,
}

export enum ValueTag {
  U64 = 0,
  I64 = 1,
  F64 = 2,
  Str = 3,
}

export enum FaultKey {
  Viewport = 1,
  Host = 2,
  Document = 3,
  Process = 4,
  Stream = 5,
  Node = 6,
  Sheet = 7,
  Rule = 8,
  Request = 9,
  Offset = 10,
  Expected = 11,
  Actual = 12,
  Phase = 13,
  Kind = 14,
  Count = 15,
  Limit = 16,
  Span = 17,
}

export enum FaultCode {
  FramingLost = 1,
  CeilingExceeded = 2,
  WrongDirection = 3,
  MalformedFields = 4,
  LinkBroken = 5,
  ClockUnavailable = 6,
  ViewportOpenRefused = 20,
  NoSuchViewport = 21,
  NoSuchHost = 22,
  HostGone = 23,
  NoSuchDocument = 24,
  DocumentGone = 25,
  MalformedUrl = 26,
  NavigateRefused = 27,
  ResizeRefused = 28,
  StaleGeneration = 29,
  ProbeDisabled = 30,
  HaltIncomplete = 31,
  CaptureUnavailable = 32,
  StaleFreezeToken = 33,
  ResyncCheckFailed = 40,
  SnapshotTooLarge = 41,
  IdentityExhausted = 42,
  InputUnknownKind = 60,
  InputNoIdentity = 61,
  InputNodeGone = 62,
  InputNotElement = 63,
  InputHalted = 64,
  InputNoTarget = 65,
  AssetNotFound = 80,
  AssetForbidden = 81,
  AssetReadFailed = 82,
  AssetOffsetGap = 83,
  AssetPhaseViolation = 84,
  AssetTooManyStreams = 85,
}

export enum CaptureKind {
  Table = 1,
  Rebuilt = 2,
  Naive = 3,
}

export enum ProbeId {
  HostTable = 1,
  RangeDigest = 2,
  IdentityMap = 3,
  RegistryState = 4,
  WriterState = 5,
  PendingDirty = 6,
}

export enum MetricId {
  BuildMicros = 1,
  OpCount = 2,
  TableSize = 3,
  DirtyCount = 4,
  EncodeMicros = 5,
}

export enum TelemetryId {
  PatchEmitted = 1,
  ResyncRequested = 2,
  ResyncDone = 3,
  ResyncFailed = 4,
  ProducerFault = 5,
  InputAdmitted = 6,
  InputRejected = 7,
}

export interface Extent {
  width: number;
  height: number;
}

export interface KeyStroke {
  key: string;
  code: string;
  mods: number;
}

export interface Metric {
  id: MetricId;
  value: bigint;
}

export interface FaultDatum {
  key: FaultKey;
  tag: ValueTag;
  num: bigint;
  text: string;
}

export const OPC_FreezeAll = 0x0F10;
export interface FreezeAll {
  timeoutMs: number;
}

export const OPC_CaptureState = 0x0F11;
export interface CaptureState {
  token: number;
  kind: CaptureKind;
}

export const OPC_ThawAll = 0x0F12;
export interface ThawAll {
  token: number;
}

export const OPC_Probe = 0x0F01;
export interface Probe {
  id: ProbeId;
  args: Uint8Array;
}

export const OPC_Shutdown = 0x0101;
export interface Shutdown {
}

export const OPC_ViewportOpen = 0x0102;
export interface ViewportOpen {
  extent: Extent;
}

export const OPC_ViewportClose = 0x0201;
export interface ViewportClose {
}

export const OPC_ViewportResize = 0x0202;
export interface ViewportResize {
  extent: Extent;
}

export const OPC_Navigate = 0x0301;
export interface Navigate {
  url: string;
}

export const OPC_Reload = 0x0302;
export interface Reload {
}

export const OPC_StopLoad = 0x0303;
export interface StopLoad {
}

export const OPC_HistoryGo = 0x0304;
export interface HistoryGo {
  delta: number;
}

export const OPC_HostResize = 0x0305;
export interface HostResize {
  extent: Extent;
}

export const OPC_Resync = 0x0306;
export interface Resync {
  force: ResyncForce;
  scope: Scope;
}

export const OPC_ClocksHalt = 0x0307;
export interface ClocksHalt {
  scope: Scope;
}

export const OPC_ClocksResume = 0x0308;
export interface ClocksResume {
  scope: Scope;
}

export const OPC_PromptRespond = 0x0309;
export interface PromptRespond {
  request: number;
  answer: Uint8Array;
}

export const OPC_Flush = 0x0401;
export interface Flush {
  generation: number;
}

export const OPC_Snapshot = 0x0402;
export interface Snapshot {
  generation: number;
}

export const OPC_InputPointerDown = 0x0410;
export interface InputPointerDown {
  generation: number;
  node: number;
  localX: number;
  localY: number;
  button: MouseButton;
}

export const OPC_InputPointerUp = 0x0411;
export interface InputPointerUp {
  generation: number;
  node: number;
  localX: number;
  localY: number;
  button: MouseButton;
}

export const OPC_InputKeyDown = 0x0412;
export interface InputKeyDown {
  stroke: KeyStroke;
}

export const OPC_InputKeyUp = 0x0413;
export interface InputKeyUp {
  stroke: KeyStroke;
}

export const OPC_InputScroll = 0x0414;
export interface InputScroll {
  generation: number;
  node: number;
  fracX: number;
  fracY: number;
}

export const OPC_AssetRequest = 0x0420;
export interface AssetRequest {
  generation: number;
  stream: number;
  url: string;
}

export const OPC_AssetCancel = 0x0421;
export interface AssetCancel {
  stream: number;
}

export const OPC_Ready = 0x8101;
export interface Ready {
}

export const OPC_Heartbeat = 0x8102;
export interface Heartbeat {
  monotonicMs: bigint;
}

export const OPC_ViewportOpened = 0x8201;
export interface ViewportOpened {
  rootHost: number;
}

export const OPC_ViewportClosed = 0x8202;
export interface ViewportClosed {
}

export const OPC_HostAttached = 0x8301;
export interface HostAttached {
  parent: number;
  viewport: number;
}

export const OPC_HostDetached = 0x8302;
export interface HostDetached {
}

export const OPC_DocumentInstalled = 0x8303;
export interface DocumentInstalled {
  generation: number;
}

export const OPC_DocumentDiscarded = 0x8304;
export interface DocumentDiscarded {
  generation: number;
}

export const OPC_Navigated = 0x8305;
export interface Navigated {
  url: string;
}

export const OPC_LoadStateChanged = 0x8306;
export interface LoadStateChanged {
  state: LoadState;
}

export const OPC_PromptRequested = 0x8307;
export interface PromptRequested {
  request: number;
  kind: PromptKind;
  description: Uint8Array;
}

export const OPC_PromptAbandoned = 0x8308;
export interface PromptAbandoned {
  request: number;
}

export const OPC_Patch = 0x8401;
export interface Patch {
  generation: number;
  sequence: number;
  flags: number;
  builtAt: number;
  metrics: Metric[];
  deltas: Uint8Array;
}

export const OPC_Snapshotted = 0x8402;
export interface Snapshotted {
  generation: number;
  sequence: number;
  digest: bigint;
  dump: Uint8Array;
}

export const OPC_AssetChunk = 0x8420;
export interface AssetChunk {
  stream: number;
  offset: bigint;
  data: Uint8Array;
}

export const OPC_AssetEnd = 0x8421;
export interface AssetEnd {
  stream: number;
  total: bigint;
}

export const OPC_AssetDenied = 0x8422;
export interface AssetDenied {
  stream: number;
  code: FaultCode;
}

export const OPC_Fault = 0x8F01;
export interface Fault {
  code: FaultCode;
  flags: number;
  origin: string;
  message: string;
  data: FaultDatum[];
}

export const OPC_FreezeResult = 0x8F10;
export interface FreezeResult {
  token: number;
  frozen: number;
  expected: number;
}

export const OPC_StateCaptured = 0x8F11;
export interface StateCaptured {
  token: number;
  host: number;
  generation: number;
  kind: CaptureKind;
  digest: bigint;
  image: Uint8Array;
}

export const OPC_ProbeResult = 0x8F03;
export interface ProbeResult {
  id: ProbeId;
  enabled: boolean;
  payload: Uint8Array;
}

export const OPC_Telemetry = 0x8F02;
export interface Telemetry {
  id: TelemetryId;
  payload: Uint8Array;
}

export function encodeExtent(w: CursorWriter, v: Extent) {
  w.i32(v.width);
  w.i32(v.height);
}
export function decodeExtent(r: CursorReader): Extent {
  return {
    width: r.i32(),
    height: r.i32(),
  };
}
export function encodeKeyStroke(w: CursorWriter, v: KeyStroke) {
  w.str(v.key);
  w.str(v.code);
  w.u8(v.mods);
}
export function decodeKeyStroke(r: CursorReader): KeyStroke {
  return {
    key: r.str(),
    code: r.str(),
    mods: r.u8(),
  };
}
export function encodeMetric(w: CursorWriter, v: Metric) {
  w.u16(v.id);
  w.u64(v.value);
}
export function decodeMetric(r: CursorReader): Metric {
  return {
    id: r.u16() as MetricId,
    value: r.u64(),
  };
}
export function encodeFaultDatum(w: CursorWriter, v: FaultDatum) {
  w.u16(v.key);
  w.u8(v.tag);
  w.u64(v.num);
  w.str(v.text);
}
export function decodeFaultDatum(r: CursorReader): FaultDatum {
  return {
    key: r.u16() as FaultKey,
    tag: r.u8() as ValueTag,
    num: r.u64(),
    text: r.str(),
  };
}
export function encodeFreezeAll(w: CursorWriter, v: FreezeAll) {
  w.u32(v.timeoutMs);
}
export function decodeFreezeAll(r: CursorReader): FreezeAll {
  return {
    timeoutMs: r.u32(),
  };
}
export function encodeFreezeAllBytes(v: FreezeAll): Uint8Array { const w = new CursorWriter(); encodeFreezeAll(w, v); return w.toUint8Array(); }
export function decodeFreezeAllBytes(b: Uint8Array): FreezeAll { const r = new CursorReader(b); const v = decodeFreezeAll(r); if (!r.ok()) throw new Error('decode FreezeAll'); return v; }
export function encodeCaptureState(w: CursorWriter, v: CaptureState) {
  w.u32(v.token);
  w.u8(v.kind);
}
export function decodeCaptureState(r: CursorReader): CaptureState {
  return {
    token: r.u32(),
    kind: r.u8() as CaptureKind,
  };
}
export function encodeCaptureStateBytes(v: CaptureState): Uint8Array { const w = new CursorWriter(); encodeCaptureState(w, v); return w.toUint8Array(); }
export function decodeCaptureStateBytes(b: Uint8Array): CaptureState { const r = new CursorReader(b); const v = decodeCaptureState(r); if (!r.ok()) throw new Error('decode CaptureState'); return v; }
export function encodeThawAll(w: CursorWriter, v: ThawAll) {
  w.u32(v.token);
}
export function decodeThawAll(r: CursorReader): ThawAll {
  return {
    token: r.u32(),
  };
}
export function encodeThawAllBytes(v: ThawAll): Uint8Array { const w = new CursorWriter(); encodeThawAll(w, v); return w.toUint8Array(); }
export function decodeThawAllBytes(b: Uint8Array): ThawAll { const r = new CursorReader(b); const v = decodeThawAll(r); if (!r.ok()) throw new Error('decode ThawAll'); return v; }
export function encodeProbe(w: CursorWriter, v: Probe) {
  w.u16(v.id);
  w.bytes(v.args);
}
export function decodeProbe(r: CursorReader): Probe {
  return {
    id: r.u16() as ProbeId,
    args: r.bytes(),
  };
}
export function encodeProbeBytes(v: Probe): Uint8Array { const w = new CursorWriter(); encodeProbe(w, v); return w.toUint8Array(); }
export function decodeProbeBytes(b: Uint8Array): Probe { const r = new CursorReader(b); const v = decodeProbe(r); if (!r.ok()) throw new Error('decode Probe'); return v; }
export function encodeShutdown(w: CursorWriter, v: Shutdown) {
}
export function decodeShutdown(r: CursorReader): Shutdown {
  return {};
}
export function encodeShutdownBytes(v: Shutdown): Uint8Array { const w = new CursorWriter(); encodeShutdown(w, v); return w.toUint8Array(); }
export function decodeShutdownBytes(b: Uint8Array): Shutdown { const r = new CursorReader(b); const v = decodeShutdown(r); if (!r.ok()) throw new Error('decode Shutdown'); return v; }
export function encodeViewportOpen(w: CursorWriter, v: ViewportOpen) {
  encodeExtent(w, v.extent);
}
export function decodeViewportOpen(r: CursorReader): ViewportOpen {
  return {
    extent: decodeExtent(r),
  };
}
export function encodeViewportOpenBytes(v: ViewportOpen): Uint8Array { const w = new CursorWriter(); encodeViewportOpen(w, v); return w.toUint8Array(); }
export function decodeViewportOpenBytes(b: Uint8Array): ViewportOpen { const r = new CursorReader(b); const v = decodeViewportOpen(r); if (!r.ok()) throw new Error('decode ViewportOpen'); return v; }
export function encodeViewportClose(w: CursorWriter, v: ViewportClose) {
}
export function decodeViewportClose(r: CursorReader): ViewportClose {
  return {};
}
export function encodeViewportCloseBytes(v: ViewportClose): Uint8Array { const w = new CursorWriter(); encodeViewportClose(w, v); return w.toUint8Array(); }
export function decodeViewportCloseBytes(b: Uint8Array): ViewportClose { const r = new CursorReader(b); const v = decodeViewportClose(r); if (!r.ok()) throw new Error('decode ViewportClose'); return v; }
export function encodeViewportResize(w: CursorWriter, v: ViewportResize) {
  encodeExtent(w, v.extent);
}
export function decodeViewportResize(r: CursorReader): ViewportResize {
  return {
    extent: decodeExtent(r),
  };
}
export function encodeViewportResizeBytes(v: ViewportResize): Uint8Array { const w = new CursorWriter(); encodeViewportResize(w, v); return w.toUint8Array(); }
export function decodeViewportResizeBytes(b: Uint8Array): ViewportResize { const r = new CursorReader(b); const v = decodeViewportResize(r); if (!r.ok()) throw new Error('decode ViewportResize'); return v; }
export function encodeNavigate(w: CursorWriter, v: Navigate) {
  w.str(v.url);
}
export function decodeNavigate(r: CursorReader): Navigate {
  return {
    url: r.str(),
  };
}
export function encodeNavigateBytes(v: Navigate): Uint8Array { const w = new CursorWriter(); encodeNavigate(w, v); return w.toUint8Array(); }
export function decodeNavigateBytes(b: Uint8Array): Navigate { const r = new CursorReader(b); const v = decodeNavigate(r); if (!r.ok()) throw new Error('decode Navigate'); return v; }
export function encodeReload(w: CursorWriter, v: Reload) {
}
export function decodeReload(r: CursorReader): Reload {
  return {};
}
export function encodeReloadBytes(v: Reload): Uint8Array { const w = new CursorWriter(); encodeReload(w, v); return w.toUint8Array(); }
export function decodeReloadBytes(b: Uint8Array): Reload { const r = new CursorReader(b); const v = decodeReload(r); if (!r.ok()) throw new Error('decode Reload'); return v; }
export function encodeStopLoad(w: CursorWriter, v: StopLoad) {
}
export function decodeStopLoad(r: CursorReader): StopLoad {
  return {};
}
export function encodeStopLoadBytes(v: StopLoad): Uint8Array { const w = new CursorWriter(); encodeStopLoad(w, v); return w.toUint8Array(); }
export function decodeStopLoadBytes(b: Uint8Array): StopLoad { const r = new CursorReader(b); const v = decodeStopLoad(r); if (!r.ok()) throw new Error('decode StopLoad'); return v; }
export function encodeHistoryGo(w: CursorWriter, v: HistoryGo) {
  w.i32(v.delta);
}
export function decodeHistoryGo(r: CursorReader): HistoryGo {
  return {
    delta: r.i32(),
  };
}
export function encodeHistoryGoBytes(v: HistoryGo): Uint8Array { const w = new CursorWriter(); encodeHistoryGo(w, v); return w.toUint8Array(); }
export function decodeHistoryGoBytes(b: Uint8Array): HistoryGo { const r = new CursorReader(b); const v = decodeHistoryGo(r); if (!r.ok()) throw new Error('decode HistoryGo'); return v; }
export function encodeHostResize(w: CursorWriter, v: HostResize) {
  encodeExtent(w, v.extent);
}
export function decodeHostResize(r: CursorReader): HostResize {
  return {
    extent: decodeExtent(r),
  };
}
export function encodeHostResizeBytes(v: HostResize): Uint8Array { const w = new CursorWriter(); encodeHostResize(w, v); return w.toUint8Array(); }
export function decodeHostResizeBytes(b: Uint8Array): HostResize { const r = new CursorReader(b); const v = decodeHostResize(r); if (!r.ok()) throw new Error('decode HostResize'); return v; }
export function encodeResync(w: CursorWriter, v: Resync) {
  w.u8(v.force);
  w.u8(v.scope);
}
export function decodeResync(r: CursorReader): Resync {
  return {
    force: r.u8() as ResyncForce,
    scope: r.u8() as Scope,
  };
}
export function encodeResyncBytes(v: Resync): Uint8Array { const w = new CursorWriter(); encodeResync(w, v); return w.toUint8Array(); }
export function decodeResyncBytes(b: Uint8Array): Resync { const r = new CursorReader(b); const v = decodeResync(r); if (!r.ok()) throw new Error('decode Resync'); return v; }
export function encodeClocksHalt(w: CursorWriter, v: ClocksHalt) {
  w.u8(v.scope);
}
export function decodeClocksHalt(r: CursorReader): ClocksHalt {
  return {
    scope: r.u8() as Scope,
  };
}
export function encodeClocksHaltBytes(v: ClocksHalt): Uint8Array { const w = new CursorWriter(); encodeClocksHalt(w, v); return w.toUint8Array(); }
export function decodeClocksHaltBytes(b: Uint8Array): ClocksHalt { const r = new CursorReader(b); const v = decodeClocksHalt(r); if (!r.ok()) throw new Error('decode ClocksHalt'); return v; }
export function encodeClocksResume(w: CursorWriter, v: ClocksResume) {
  w.u8(v.scope);
}
export function decodeClocksResume(r: CursorReader): ClocksResume {
  return {
    scope: r.u8() as Scope,
  };
}
export function encodeClocksResumeBytes(v: ClocksResume): Uint8Array { const w = new CursorWriter(); encodeClocksResume(w, v); return w.toUint8Array(); }
export function decodeClocksResumeBytes(b: Uint8Array): ClocksResume { const r = new CursorReader(b); const v = decodeClocksResume(r); if (!r.ok()) throw new Error('decode ClocksResume'); return v; }
export function encodePromptRespond(w: CursorWriter, v: PromptRespond) {
  w.u32(v.request);
  w.bytes(v.answer);
}
export function decodePromptRespond(r: CursorReader): PromptRespond {
  return {
    request: r.u32(),
    answer: r.bytes(),
  };
}
export function encodePromptRespondBytes(v: PromptRespond): Uint8Array { const w = new CursorWriter(); encodePromptRespond(w, v); return w.toUint8Array(); }
export function decodePromptRespondBytes(b: Uint8Array): PromptRespond { const r = new CursorReader(b); const v = decodePromptRespond(r); if (!r.ok()) throw new Error('decode PromptRespond'); return v; }
export function encodeFlush(w: CursorWriter, v: Flush) {
  w.u32(v.generation);
}
export function decodeFlush(r: CursorReader): Flush {
  return {
    generation: r.u32(),
  };
}
export function encodeFlushBytes(v: Flush): Uint8Array { const w = new CursorWriter(); encodeFlush(w, v); return w.toUint8Array(); }
export function decodeFlushBytes(b: Uint8Array): Flush { const r = new CursorReader(b); const v = decodeFlush(r); if (!r.ok()) throw new Error('decode Flush'); return v; }
export function encodeSnapshot(w: CursorWriter, v: Snapshot) {
  w.u32(v.generation);
}
export function decodeSnapshot(r: CursorReader): Snapshot {
  return {
    generation: r.u32(),
  };
}
export function encodeSnapshotBytes(v: Snapshot): Uint8Array { const w = new CursorWriter(); encodeSnapshot(w, v); return w.toUint8Array(); }
export function decodeSnapshotBytes(b: Uint8Array): Snapshot { const r = new CursorReader(b); const v = decodeSnapshot(r); if (!r.ok()) throw new Error('decode Snapshot'); return v; }
export function encodeInputPointerDown(w: CursorWriter, v: InputPointerDown) {
  w.u32(v.generation);
  w.u32(v.node);
  w.u16(v.localX);
  w.u16(v.localY);
  w.u8(v.button);
}
export function decodeInputPointerDown(r: CursorReader): InputPointerDown {
  return {
    generation: r.u32(),
    node: r.u32(),
    localX: r.u16(),
    localY: r.u16(),
    button: r.u8() as MouseButton,
  };
}
export function encodeInputPointerDownBytes(v: InputPointerDown): Uint8Array { const w = new CursorWriter(); encodeInputPointerDown(w, v); return w.toUint8Array(); }
export function decodeInputPointerDownBytes(b: Uint8Array): InputPointerDown { const r = new CursorReader(b); const v = decodeInputPointerDown(r); if (!r.ok()) throw new Error('decode InputPointerDown'); return v; }
export function encodeInputPointerUp(w: CursorWriter, v: InputPointerUp) {
  w.u32(v.generation);
  w.u32(v.node);
  w.u16(v.localX);
  w.u16(v.localY);
  w.u8(v.button);
}
export function decodeInputPointerUp(r: CursorReader): InputPointerUp {
  return {
    generation: r.u32(),
    node: r.u32(),
    localX: r.u16(),
    localY: r.u16(),
    button: r.u8() as MouseButton,
  };
}
export function encodeInputPointerUpBytes(v: InputPointerUp): Uint8Array { const w = new CursorWriter(); encodeInputPointerUp(w, v); return w.toUint8Array(); }
export function decodeInputPointerUpBytes(b: Uint8Array): InputPointerUp { const r = new CursorReader(b); const v = decodeInputPointerUp(r); if (!r.ok()) throw new Error('decode InputPointerUp'); return v; }
export function encodeInputKeyDown(w: CursorWriter, v: InputKeyDown) {
  encodeKeyStroke(w, v.stroke);
}
export function decodeInputKeyDown(r: CursorReader): InputKeyDown {
  return {
    stroke: decodeKeyStroke(r),
  };
}
export function encodeInputKeyDownBytes(v: InputKeyDown): Uint8Array { const w = new CursorWriter(); encodeInputKeyDown(w, v); return w.toUint8Array(); }
export function decodeInputKeyDownBytes(b: Uint8Array): InputKeyDown { const r = new CursorReader(b); const v = decodeInputKeyDown(r); if (!r.ok()) throw new Error('decode InputKeyDown'); return v; }
export function encodeInputKeyUp(w: CursorWriter, v: InputKeyUp) {
  encodeKeyStroke(w, v.stroke);
}
export function decodeInputKeyUp(r: CursorReader): InputKeyUp {
  return {
    stroke: decodeKeyStroke(r),
  };
}
export function encodeInputKeyUpBytes(v: InputKeyUp): Uint8Array { const w = new CursorWriter(); encodeInputKeyUp(w, v); return w.toUint8Array(); }
export function decodeInputKeyUpBytes(b: Uint8Array): InputKeyUp { const r = new CursorReader(b); const v = decodeInputKeyUp(r); if (!r.ok()) throw new Error('decode InputKeyUp'); return v; }
export function encodeInputScroll(w: CursorWriter, v: InputScroll) {
  w.u32(v.generation);
  w.u32(v.node);
  w.u16(v.fracX);
  w.u16(v.fracY);
}
export function decodeInputScroll(r: CursorReader): InputScroll {
  return {
    generation: r.u32(),
    node: r.u32(),
    fracX: r.u16(),
    fracY: r.u16(),
  };
}
export function encodeInputScrollBytes(v: InputScroll): Uint8Array { const w = new CursorWriter(); encodeInputScroll(w, v); return w.toUint8Array(); }
export function decodeInputScrollBytes(b: Uint8Array): InputScroll { const r = new CursorReader(b); const v = decodeInputScroll(r); if (!r.ok()) throw new Error('decode InputScroll'); return v; }
export function encodeAssetRequest(w: CursorWriter, v: AssetRequest) {
  w.u32(v.generation);
  w.u32(v.stream);
  w.str(v.url);
}
export function decodeAssetRequest(r: CursorReader): AssetRequest {
  return {
    generation: r.u32(),
    stream: r.u32(),
    url: r.str(),
  };
}
export function encodeAssetRequestBytes(v: AssetRequest): Uint8Array { const w = new CursorWriter(); encodeAssetRequest(w, v); return w.toUint8Array(); }
export function decodeAssetRequestBytes(b: Uint8Array): AssetRequest { const r = new CursorReader(b); const v = decodeAssetRequest(r); if (!r.ok()) throw new Error('decode AssetRequest'); return v; }
export function encodeAssetCancel(w: CursorWriter, v: AssetCancel) {
  w.u32(v.stream);
}
export function decodeAssetCancel(r: CursorReader): AssetCancel {
  return {
    stream: r.u32(),
  };
}
export function encodeAssetCancelBytes(v: AssetCancel): Uint8Array { const w = new CursorWriter(); encodeAssetCancel(w, v); return w.toUint8Array(); }
export function decodeAssetCancelBytes(b: Uint8Array): AssetCancel { const r = new CursorReader(b); const v = decodeAssetCancel(r); if (!r.ok()) throw new Error('decode AssetCancel'); return v; }
export function encodeReady(w: CursorWriter, v: Ready) {
}
export function decodeReady(r: CursorReader): Ready {
  return {};
}
export function encodeReadyBytes(v: Ready): Uint8Array { const w = new CursorWriter(); encodeReady(w, v); return w.toUint8Array(); }
export function decodeReadyBytes(b: Uint8Array): Ready { const r = new CursorReader(b); const v = decodeReady(r); if (!r.ok()) throw new Error('decode Ready'); return v; }
export function encodeHeartbeat(w: CursorWriter, v: Heartbeat) {
  w.u64(v.monotonicMs);
}
export function decodeHeartbeat(r: CursorReader): Heartbeat {
  return {
    monotonicMs: r.u64(),
  };
}
export function encodeHeartbeatBytes(v: Heartbeat): Uint8Array { const w = new CursorWriter(); encodeHeartbeat(w, v); return w.toUint8Array(); }
export function decodeHeartbeatBytes(b: Uint8Array): Heartbeat { const r = new CursorReader(b); const v = decodeHeartbeat(r); if (!r.ok()) throw new Error('decode Heartbeat'); return v; }
export function encodeViewportOpened(w: CursorWriter, v: ViewportOpened) {
  w.u32(v.rootHost);
}
export function decodeViewportOpened(r: CursorReader): ViewportOpened {
  return {
    rootHost: r.u32(),
  };
}
export function encodeViewportOpenedBytes(v: ViewportOpened): Uint8Array { const w = new CursorWriter(); encodeViewportOpened(w, v); return w.toUint8Array(); }
export function decodeViewportOpenedBytes(b: Uint8Array): ViewportOpened { const r = new CursorReader(b); const v = decodeViewportOpened(r); if (!r.ok()) throw new Error('decode ViewportOpened'); return v; }
export function encodeViewportClosed(w: CursorWriter, v: ViewportClosed) {
}
export function decodeViewportClosed(r: CursorReader): ViewportClosed {
  return {};
}
export function encodeViewportClosedBytes(v: ViewportClosed): Uint8Array { const w = new CursorWriter(); encodeViewportClosed(w, v); return w.toUint8Array(); }
export function decodeViewportClosedBytes(b: Uint8Array): ViewportClosed { const r = new CursorReader(b); const v = decodeViewportClosed(r); if (!r.ok()) throw new Error('decode ViewportClosed'); return v; }
export function encodeHostAttached(w: CursorWriter, v: HostAttached) {
  w.u32(v.parent);
  w.u32(v.viewport);
}
export function decodeHostAttached(r: CursorReader): HostAttached {
  return {
    parent: r.u32(),
    viewport: r.u32(),
  };
}
export function encodeHostAttachedBytes(v: HostAttached): Uint8Array { const w = new CursorWriter(); encodeHostAttached(w, v); return w.toUint8Array(); }
export function decodeHostAttachedBytes(b: Uint8Array): HostAttached { const r = new CursorReader(b); const v = decodeHostAttached(r); if (!r.ok()) throw new Error('decode HostAttached'); return v; }
export function encodeHostDetached(w: CursorWriter, v: HostDetached) {
}
export function decodeHostDetached(r: CursorReader): HostDetached {
  return {};
}
export function encodeHostDetachedBytes(v: HostDetached): Uint8Array { const w = new CursorWriter(); encodeHostDetached(w, v); return w.toUint8Array(); }
export function decodeHostDetachedBytes(b: Uint8Array): HostDetached { const r = new CursorReader(b); const v = decodeHostDetached(r); if (!r.ok()) throw new Error('decode HostDetached'); return v; }
export function encodeDocumentInstalled(w: CursorWriter, v: DocumentInstalled) {
  w.u32(v.generation);
}
export function decodeDocumentInstalled(r: CursorReader): DocumentInstalled {
  return {
    generation: r.u32(),
  };
}
export function encodeDocumentInstalledBytes(v: DocumentInstalled): Uint8Array { const w = new CursorWriter(); encodeDocumentInstalled(w, v); return w.toUint8Array(); }
export function decodeDocumentInstalledBytes(b: Uint8Array): DocumentInstalled { const r = new CursorReader(b); const v = decodeDocumentInstalled(r); if (!r.ok()) throw new Error('decode DocumentInstalled'); return v; }
export function encodeDocumentDiscarded(w: CursorWriter, v: DocumentDiscarded) {
  w.u32(v.generation);
}
export function decodeDocumentDiscarded(r: CursorReader): DocumentDiscarded {
  return {
    generation: r.u32(),
  };
}
export function encodeDocumentDiscardedBytes(v: DocumentDiscarded): Uint8Array { const w = new CursorWriter(); encodeDocumentDiscarded(w, v); return w.toUint8Array(); }
export function decodeDocumentDiscardedBytes(b: Uint8Array): DocumentDiscarded { const r = new CursorReader(b); const v = decodeDocumentDiscarded(r); if (!r.ok()) throw new Error('decode DocumentDiscarded'); return v; }
export function encodeNavigated(w: CursorWriter, v: Navigated) {
  w.str(v.url);
}
export function decodeNavigated(r: CursorReader): Navigated {
  return {
    url: r.str(),
  };
}
export function encodeNavigatedBytes(v: Navigated): Uint8Array { const w = new CursorWriter(); encodeNavigated(w, v); return w.toUint8Array(); }
export function decodeNavigatedBytes(b: Uint8Array): Navigated { const r = new CursorReader(b); const v = decodeNavigated(r); if (!r.ok()) throw new Error('decode Navigated'); return v; }
export function encodeLoadStateChanged(w: CursorWriter, v: LoadStateChanged) {
  w.u8(v.state);
}
export function decodeLoadStateChanged(r: CursorReader): LoadStateChanged {
  return {
    state: r.u8() as LoadState,
  };
}
export function encodeLoadStateChangedBytes(v: LoadStateChanged): Uint8Array { const w = new CursorWriter(); encodeLoadStateChanged(w, v); return w.toUint8Array(); }
export function decodeLoadStateChangedBytes(b: Uint8Array): LoadStateChanged { const r = new CursorReader(b); const v = decodeLoadStateChanged(r); if (!r.ok()) throw new Error('decode LoadStateChanged'); return v; }
export function encodePromptRequested(w: CursorWriter, v: PromptRequested) {
  w.u32(v.request);
  w.u8(v.kind);
  w.bytes(v.description);
}
export function decodePromptRequested(r: CursorReader): PromptRequested {
  return {
    request: r.u32(),
    kind: r.u8() as PromptKind,
    description: r.bytes(),
  };
}
export function encodePromptRequestedBytes(v: PromptRequested): Uint8Array { const w = new CursorWriter(); encodePromptRequested(w, v); return w.toUint8Array(); }
export function decodePromptRequestedBytes(b: Uint8Array): PromptRequested { const r = new CursorReader(b); const v = decodePromptRequested(r); if (!r.ok()) throw new Error('decode PromptRequested'); return v; }
export function encodePromptAbandoned(w: CursorWriter, v: PromptAbandoned) {
  w.u32(v.request);
}
export function decodePromptAbandoned(r: CursorReader): PromptAbandoned {
  return {
    request: r.u32(),
  };
}
export function encodePromptAbandonedBytes(v: PromptAbandoned): Uint8Array { const w = new CursorWriter(); encodePromptAbandoned(w, v); return w.toUint8Array(); }
export function decodePromptAbandonedBytes(b: Uint8Array): PromptAbandoned { const r = new CursorReader(b); const v = decodePromptAbandoned(r); if (!r.ok()) throw new Error('decode PromptAbandoned'); return v; }
export function encodePatch(w: CursorWriter, v: Patch) {
  w.u32(v.generation);
  w.u32(v.sequence);
  w.u16(v.flags);
  w.u32(v.builtAt);
  { w.u8(v.metrics.length); for (const _it of v.metrics) { encodeMetric(w, _it); } };
  w.bytes(v.deltas);
}
export function decodePatch(r: CursorReader): Patch {
  return {
    generation: r.u32(),
    sequence: r.u32(),
    flags: r.u16(),
    builtAt: r.u32(),
    metrics: (() => { const n = r.u8(); const a: Metric[] = []; for (let i = 0; i < n; i++) a.push(decodeMetric(r)); return a; })(),
    deltas: r.bytes(),
  };
}
export function encodePatchBytes(v: Patch): Uint8Array { const w = new CursorWriter(); encodePatch(w, v); return w.toUint8Array(); }
export function decodePatchBytes(b: Uint8Array): Patch { const r = new CursorReader(b); const v = decodePatch(r); if (!r.ok()) throw new Error('decode Patch'); return v; }
export function encodeSnapshotted(w: CursorWriter, v: Snapshotted) {
  w.u32(v.generation);
  w.u32(v.sequence);
  w.u64(v.digest);
  w.bytes(v.dump);
}
export function decodeSnapshotted(r: CursorReader): Snapshotted {
  return {
    generation: r.u32(),
    sequence: r.u32(),
    digest: r.u64(),
    dump: r.bytes(),
  };
}
export function encodeSnapshottedBytes(v: Snapshotted): Uint8Array { const w = new CursorWriter(); encodeSnapshotted(w, v); return w.toUint8Array(); }
export function decodeSnapshottedBytes(b: Uint8Array): Snapshotted { const r = new CursorReader(b); const v = decodeSnapshotted(r); if (!r.ok()) throw new Error('decode Snapshotted'); return v; }
export function encodeAssetChunk(w: CursorWriter, v: AssetChunk) {
  w.u32(v.stream);
  w.u64(v.offset);
  w.bytes(v.data);
}
export function decodeAssetChunk(r: CursorReader): AssetChunk {
  return {
    stream: r.u32(),
    offset: r.u64(),
    data: r.bytes(),
  };
}
export function encodeAssetChunkBytes(v: AssetChunk): Uint8Array { const w = new CursorWriter(); encodeAssetChunk(w, v); return w.toUint8Array(); }
export function decodeAssetChunkBytes(b: Uint8Array): AssetChunk { const r = new CursorReader(b); const v = decodeAssetChunk(r); if (!r.ok()) throw new Error('decode AssetChunk'); return v; }
export function encodeAssetEnd(w: CursorWriter, v: AssetEnd) {
  w.u32(v.stream);
  w.u64(v.total);
}
export function decodeAssetEnd(r: CursorReader): AssetEnd {
  return {
    stream: r.u32(),
    total: r.u64(),
  };
}
export function encodeAssetEndBytes(v: AssetEnd): Uint8Array { const w = new CursorWriter(); encodeAssetEnd(w, v); return w.toUint8Array(); }
export function decodeAssetEndBytes(b: Uint8Array): AssetEnd { const r = new CursorReader(b); const v = decodeAssetEnd(r); if (!r.ok()) throw new Error('decode AssetEnd'); return v; }
export function encodeAssetDenied(w: CursorWriter, v: AssetDenied) {
  w.u32(v.stream);
  w.u16(v.code);
}
export function decodeAssetDenied(r: CursorReader): AssetDenied {
  return {
    stream: r.u32(),
    code: r.u16() as FaultCode,
  };
}
export function encodeAssetDeniedBytes(v: AssetDenied): Uint8Array { const w = new CursorWriter(); encodeAssetDenied(w, v); return w.toUint8Array(); }
export function decodeAssetDeniedBytes(b: Uint8Array): AssetDenied { const r = new CursorReader(b); const v = decodeAssetDenied(r); if (!r.ok()) throw new Error('decode AssetDenied'); return v; }
export function encodeFault(w: CursorWriter, v: Fault) {
  w.u16(v.code);
  w.u32(v.flags);
  w.str(v.origin);
  w.str(v.message);
  { w.u8(v.data.length); for (const _it of v.data) { encodeFaultDatum(w, _it); } };
}
export function decodeFault(r: CursorReader): Fault {
  return {
    code: r.u16() as FaultCode,
    flags: r.u32(),
    origin: r.str(),
    message: r.str(),
    data: (() => { const n = r.u8(); const a: FaultDatum[] = []; for (let i = 0; i < n; i++) a.push(decodeFaultDatum(r)); return a; })(),
  };
}
export function encodeFaultBytes(v: Fault): Uint8Array { const w = new CursorWriter(); encodeFault(w, v); return w.toUint8Array(); }
export function decodeFaultBytes(b: Uint8Array): Fault { const r = new CursorReader(b); const v = decodeFault(r); if (!r.ok()) throw new Error('decode Fault'); return v; }
export function encodeFreezeResult(w: CursorWriter, v: FreezeResult) {
  w.u32(v.token);
  w.u32(v.frozen);
  w.u32(v.expected);
}
export function decodeFreezeResult(r: CursorReader): FreezeResult {
  return {
    token: r.u32(),
    frozen: r.u32(),
    expected: r.u32(),
  };
}
export function encodeFreezeResultBytes(v: FreezeResult): Uint8Array { const w = new CursorWriter(); encodeFreezeResult(w, v); return w.toUint8Array(); }
export function decodeFreezeResultBytes(b: Uint8Array): FreezeResult { const r = new CursorReader(b); const v = decodeFreezeResult(r); if (!r.ok()) throw new Error('decode FreezeResult'); return v; }
export function encodeStateCaptured(w: CursorWriter, v: StateCaptured) {
  w.u32(v.token);
  w.u32(v.host);
  w.u32(v.generation);
  w.u8(v.kind);
  w.u64(v.digest);
  w.bytes(v.image);
}
export function decodeStateCaptured(r: CursorReader): StateCaptured {
  return {
    token: r.u32(),
    host: r.u32(),
    generation: r.u32(),
    kind: r.u8() as CaptureKind,
    digest: r.u64(),
    image: r.bytes(),
  };
}
export function encodeStateCapturedBytes(v: StateCaptured): Uint8Array { const w = new CursorWriter(); encodeStateCaptured(w, v); return w.toUint8Array(); }
export function decodeStateCapturedBytes(b: Uint8Array): StateCaptured { const r = new CursorReader(b); const v = decodeStateCaptured(r); if (!r.ok()) throw new Error('decode StateCaptured'); return v; }
export function encodeProbeResult(w: CursorWriter, v: ProbeResult) {
  w.u16(v.id);
  w.bool(v.enabled);
  w.bytes(v.payload);
}
export function decodeProbeResult(r: CursorReader): ProbeResult {
  return {
    id: r.u16() as ProbeId,
    enabled: r.bool(),
    payload: r.bytes(),
  };
}
export function encodeProbeResultBytes(v: ProbeResult): Uint8Array { const w = new CursorWriter(); encodeProbeResult(w, v); return w.toUint8Array(); }
export function decodeProbeResultBytes(b: Uint8Array): ProbeResult { const r = new CursorReader(b); const v = decodeProbeResult(r); if (!r.ok()) throw new Error('decode ProbeResult'); return v; }
export function encodeTelemetry(w: CursorWriter, v: Telemetry) {
  w.u16(v.id);
  w.bytes(v.payload);
}
export function decodeTelemetry(r: CursorReader): Telemetry {
  return {
    id: r.u16() as TelemetryId,
    payload: r.bytes(),
  };
}
export function encodeTelemetryBytes(v: Telemetry): Uint8Array { const w = new CursorWriter(); encodeTelemetry(w, v); return w.toUint8Array(); }
export function decodeTelemetryBytes(b: Uint8Array): Telemetry { const r = new CursorReader(b); const v = decodeTelemetry(r); if (!r.ok()) throw new Error('decode Telemetry'); return v; }

export const MESSAGE_NAMES: Record<number, string> = {
  0x0F10: "FreezeAll",
  0x0F11: "CaptureState",
  0x0F12: "ThawAll",
  0x0F01: "Probe",
  0x0101: "Shutdown",
  0x0102: "ViewportOpen",
  0x0201: "ViewportClose",
  0x0202: "ViewportResize",
  0x0301: "Navigate",
  0x0302: "Reload",
  0x0303: "StopLoad",
  0x0304: "HistoryGo",
  0x0305: "HostResize",
  0x0306: "Resync",
  0x0307: "ClocksHalt",
  0x0308: "ClocksResume",
  0x0309: "PromptRespond",
  0x0401: "Flush",
  0x0402: "Snapshot",
  0x0410: "InputPointerDown",
  0x0411: "InputPointerUp",
  0x0412: "InputKeyDown",
  0x0413: "InputKeyUp",
  0x0414: "InputScroll",
  0x0420: "AssetRequest",
  0x0421: "AssetCancel",
  0x8101: "Ready",
  0x8102: "Heartbeat",
  0x8201: "ViewportOpened",
  0x8202: "ViewportClosed",
  0x8301: "HostAttached",
  0x8302: "HostDetached",
  0x8303: "DocumentInstalled",
  0x8304: "DocumentDiscarded",
  0x8305: "Navigated",
  0x8306: "LoadStateChanged",
  0x8307: "PromptRequested",
  0x8308: "PromptAbandoned",
  0x8401: "Patch",
  0x8402: "Snapshotted",
  0x8420: "AssetChunk",
  0x8421: "AssetEnd",
  0x8422: "AssetDenied",
  0x8F01: "Fault",
  0x8F10: "FreezeResult",
  0x8F11: "StateCaptured",
  0x8F03: "ProbeResult",
  0x8F02: "Telemetry",
};
