import { useState } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { adminChangePassword, AdminApiError } from '@/lib/adminFetch'
import { HelperCallout, InlineValidation, PageHeader, SaveFeedback } from '@/features/admin/components'
import { useAdminToast } from '@/features/admin/shell/AdminToastContext'
export function ChangePasswordPage() { const navigate = useNavigate(); const toast = useAdminToast(); const [current, setCurrent] = useState(''); const [next, setNext] = useState(''); const [confirm, setConfirm] = useState(''); const [error, setError] = useState(''); const [pending, setPending] = useState(false); const mismatch = confirm && confirm !== next ? 'Passwords do not match.' : ''; const submit = async (event: React.FormEvent) => { event.preventDefault(); setError(''); if (!current || next.length < 4 || next !== confirm) return; setPending(true); try { await adminChangePassword(current, next); toast.success('Password updated. Sign in again.'); navigate('/admin/login', { replace: true }) } catch (cause) { const message = cause instanceof AdminApiError ? cause.message : ''; setError(message === 'invalid_credentials' ? 'Current password is incorrect.' : message === 'password_too_short' ? 'New password is too short.' : 'Password update failed. Try again.') } finally { setPending(false) } }; return <div className="max-w-xl space-y-6"><PageHeader title="Change password" /><HelperCallout tone="warning">If you are still using the install default, change it before exposing this control plane.</HelperCallout><form className="space-y-4" onSubmit={submit}><div><Label htmlFor="current-password">Current password</Label><Input id="current-password" type="password" autoComplete="current-password" value={current} disabled={pending} onChange={(event) => setCurrent(event.target.value)} /></div><div><Label htmlFor="new-password">New password</Label><Input id="new-password" type="password" autoComplete="new-password" value={next} disabled={pending} onChange={(event) => setNext(event.target.value)} /><InlineValidation tone="hint" message="At least 4 characters" /></div><div><Label htmlFor="confirm-password">Confirm new password</Label><Input id="confirm-password" type="password" autoComplete="new-password" value={confirm} disabled={pending} aria-invalid={Boolean(mismatch)} aria-describedby="confirm-password-error" onChange={(event) => setConfirm(event.target.value)} /><InlineValidation id="confirm-password-error" message={mismatch} /></div>{error ? <SaveFeedback mode="inline-error" message={error} /> : null}<div className="flex gap-2"><Button type="submit" disabled={pending || !current || next.length < 4 || Boolean(mismatch)}>{pending ? 'Updating…' : 'Update password'}</Button><Button asChild variant="outline"><Link to="/admin">Cancel</Link></Button></div></form></div> }
