/** Shared wire models — sidecar imports these to decode Virtual→host frames. */
export { NONE_DOM_NODE_KEY, type DomNodeKey } from './domNodeKey';
export {
  OpCode,
  opCodeName,
  opCodePlane,
} from './opcodes';
export {
  FRAME_WIRE_VERSION,
  createLiveFrame,
  type ChildListMode,
  type ChildListOp,
  type ChildRef,
  type DomNodeSnapshot,
  type Frame,
  type FrameFlags,
  type FrameOp,
  type PatchOp,
  type ScrollElementOp,
  type ScrollViewportOp,
} from './frame';
export {
  TELEMETRY_WIRE_VERSION,
  DEFAULT_TELEMETRY_CONFIG,
  LAB_TELEMETRY_DEFAULTS,
  TELEMETRY_BOOL_CAPS,
  CHILD_LIST_FACT_CAP,
  isProjectionTelemetryMessage,
  desyncPhase,
  isRepeatedConcat,
  type ProjectionTelemetryCapabilities,
  type ProjectionTelemetryConfig,
  type ProjectionTelemetryMessage,
  type TelemetryAggregate,
  type TelemetryApplyDecision,
  type TelemetryApplyOverrun,
  type TelemetryApplyResult,
  type TelemetryBuilderStats,
  type TelemetryClockStalled,
  type TelemetryDesynced,
  type TelemetryEncoder,
  type TelemetryEstablishCompleted,
  type TelemetryEstablishFailed,
  type TelemetryEstablishStarted,
  type TelemetryFrameDecision,
  type TelemetryFrameEmitted,
  type TelemetryHandoff,
  type TelemetryParityFingerprint,
  type TelemetryRateChanged,
  type TelemetryTransportDeferred,
  type ChildListDecisionFact,
  type DirtyCard,
} from './telemetry';
